-- MyRaices v12 — Orders + Square payment tracking
create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity (start with 1001),
  status text not null default 'pending_payment',
  payment_status text not null default 'PENDING',
  payment_provider text not null default 'square',
  currency text not null default 'USD',
  subtotal_cents integer not null check (subtotal_cents >= 0),
  delivery_cents integer not null default 0 check (delivery_cents >= 0),
  tax_cents integer not null default 0 check (tax_cents >= 0),
  total_cents integer not null check (total_cents >= 0),
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  delivery_address text not null,
  delivery_apt text,
  delivery_city text not null,
  delivery_state text not null,
  delivery_zip text not null,
  delivery_zone text,
  google_place_id text,
  delivery_notes text,
  checkout_environment text not null default 'sandbox',
  square_order_id text unique,
  square_payment_link_id text,
  square_payment_id text,
  provider_error text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists orders_order_number_idx on public.orders(order_number);
create index if not exists orders_customer_email_idx on public.orders(lower(customer_email));
create index if not exists orders_status_idx on public.orders(status, created_at desc);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  sku text not null,
  product_name text not null,
  variant text,
  quantity integer not null check (quantity > 0),
  unit_price_cents integer not null check (unit_price_cents >= 0),
  line_total_cents integer not null check (line_total_cents >= 0),
  created_at timestamptz not null default now()
);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
-- No public policies: browser users cannot create or read orders directly.
-- Netlify Functions use SUPABASE_SERVICE_ROLE_KEY and bypass RLS.
