-- MyRaíces + NURAI unified product catalog v1.0
-- Run once in the MyRaíces Supabase project.
begin;

alter table public.products add column if not exists display_category text;
alter table public.products add column if not exists display_collection text;
alter table public.products add column if not exists subcategory_label text;
alter table public.products add column if not exists unit_label text;
alter table public.products add column if not exists unit_weight_label text;
alter table public.products add column if not exists net_weight_label text;
alter table public.products add column if not exists long_description_es text;
alter table public.products add column if not exists long_description_en text;
alter table public.products add column if not exists benefits jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists ingredients_text text;
alter table public.products add column if not exists conservation_text text;
alter table public.products add column if not exists preparation_text text;
alter table public.products add column if not exists moment_text text;
alter table public.products add column if not exists related_hint text;
alter table public.products add column if not exists variants jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists taxable boolean;

-- Archive the former NURAI-only test catalog without deleting it.
update public.products set status='archived', updated_at=now() where sku not in ('RA-AR-001', 'RA-AR-002', 'RA-AR-003', 'RA-AR-004', 'RA-AR-005', 'RA-AR-006', 'RA-AR-007', 'RA-AR-008', 'RA-EM-001', 'RA-EM-002', 'RA-EM-003', 'RA-EM-004', 'RA-EM-005', 'RA-EM-006', 'RA-EM-007', 'RA-PC-001', 'RA-PC-002', 'RA-PC-003', 'RA-PC-004', 'RA-PC-005', 'RA-TM-001', 'RA-TM-002', 'RA-TM-003', 'RA-TM-004', 'RA-RC-001', 'RA-RB-001', 'RA-DE-001', 'RA-DE-002', 'RA-DE-003', 'RA-HM-001', 'RA-HM-006', 'RA-HM-002', 'RA-HM-003', 'RA-HM-004', 'RA-HM-005', 'RA-LB-001', 'RA-LB-002', 'RA-LB-003', 'RA-LB-004');

insert into public.products (
  sku,
  name_es,
  name_en,
  description_es,
  description_en,
  collection,
  category,
  price,
  unit_price,
  pack_size,
  weight,
  stock,
  status,
  featured,
  image_url,
  sort_order,
  units_per_pack,
  weight_value,
  weight_unit,
  minimum_stock,
  ideal_stock,
  slug,
  meta_title,
  meta_description,
  tags,
  display_category,
  display_collection,
  subcategory_label,
  unit_label,
  unit_weight_label,
  net_weight_label,
  long_description_es,
  long_description_en,
  benefits,
  ingredients_text,
  conservation_text,
  preparation_text,
  moment_text,
  related_hint,
  variants,
  taxable
) values
  ('RA-AR-001', 'Yuca Clásica', 'Yuca Clásica', 'Arepa artesanal de yuca clásica elaborada para calentar, servir y disfrutar en casa.', 'Arepa artesanal de yuca clásica elaborada para calentar, servir y disfrutar en casa.', 'Cocina', 'Arepas', 18, 3.0, '6 Paquete', '680 g (24 oz)', null, 'active', false, 'https://myraices.com/assets/products/arepas/arepa-yuca-clasica.jpg', 1, 6, 113.0, 'g', 0, 0, 'yuca-clasica', 'Yuca Clásica', 'Arepa artesanal de yuca clásica elaborada para calentar, servir y disfrutar en casa.', '{}'::text[], 'Kitchen', 'Signature Arepas', 'Arepas', 'Paquete', '113 g (4 oz)', '680 g (24 oz)', 'Yuca Clásica forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', 'Yuca Clásica forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', '["Hechas con raíces e ingredientes reales", "Sin conservantes artificiales", "Listas para calentar y compartir"]'::jsonb, 'Yuca y mezcla natural según variedad.', 'Mantener congelado. Cerrar bien el empaque después de abrir.', 'Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.', 'Desayuno, cena ligera o acompañamiento saludable.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-AR-002', 'Yuca + Zanahoria', 'Yuca + Zanahoria', 'Arepa artesanal de yuca + zanahoria elaborada para calentar, servir y disfrutar en casa.', 'Arepa artesanal de yuca + zanahoria elaborada para calentar, servir y disfrutar en casa.', 'Cocina', 'Arepas', 19, 3.17, '6 Paquete', '680 g (24 oz)', null, 'active', false, 'https://myraices.com/assets/products/arepas/arepa-yuca-zanahoria.jpg', 2, 6, 113.0, 'g', 0, 0, 'yuca-zanahoria', 'Yuca + Zanahoria', 'Arepa artesanal de yuca + zanahoria elaborada para calentar, servir y disfrutar en casa.', '{}'::text[], 'Kitchen', 'Signature Arepas', 'Arepas', 'Paquete', '113 g (4 oz)', '680 g (24 oz)', 'Yuca + Zanahoria forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', 'Yuca + Zanahoria forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', '["Hechas con raíces e ingredientes reales", "Sin conservantes artificiales", "Listas para calentar y compartir"]'::jsonb, 'Yuca y mezcla natural según variedad.', 'Mantener congelado. Cerrar bien el empaque después de abrir.', 'Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.', 'Desayuno, cena ligera o acompañamiento saludable.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-AR-003', 'Yuca + Remolacha', 'Yuca + Remolacha', 'Arepa artesanal de yuca + remolacha elaborada para calentar, servir y disfrutar en casa.', 'Arepa artesanal de yuca + remolacha elaborada para calentar, servir y disfrutar en casa.', 'Cocina', 'Arepas', 19, 3.17, '6 Paquete', '680 g (24 oz)', null, 'active', false, 'https://myraices.com/assets/products/arepas/arepa-yuca-remolacha.jpg', 3, 6, 113.0, 'g', 0, 0, 'yuca-remolacha', 'Yuca + Remolacha', 'Arepa artesanal de yuca + remolacha elaborada para calentar, servir y disfrutar en casa.', '{}'::text[], 'Kitchen', 'Signature Arepas', 'Arepas', 'Paquete', '113 g (4 oz)', '680 g (24 oz)', 'Yuca + Remolacha forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', 'Yuca + Remolacha forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', '["Hechas con raíces e ingredientes reales", "Sin conservantes artificiales", "Listas para calentar y compartir"]'::jsonb, 'Yuca y mezcla natural según variedad.', 'Mantener congelado. Cerrar bien el empaque después de abrir.', 'Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.', 'Desayuno, cena ligera o acompañamiento saludable.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-AR-004', 'Yuca + Cúrcuma', 'Yuca + Cúrcuma', 'Arepa artesanal de yuca + cúrcuma elaborada para calentar, servir y disfrutar en casa.', 'Arepa artesanal de yuca + cúrcuma elaborada para calentar, servir y disfrutar en casa.', 'Cocina', 'Arepas', 19, 3.17, '6 Paquete', '680 g (24 oz)', null, 'active', false, 'https://myraices.com/assets/products/arepas/arepa-yuca-curcuma.jpg', 4, 6, 113.0, 'g', 0, 0, 'yuca-curcuma', 'Yuca + Cúrcuma', 'Arepa artesanal de yuca + cúrcuma elaborada para calentar, servir y disfrutar en casa.', '{}'::text[], 'Kitchen', 'Signature Arepas', 'Arepas', 'Paquete', '113 g (4 oz)', '680 g (24 oz)', 'Yuca + Cúrcuma forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', 'Yuca + Cúrcuma forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', '["Hechas con raíces e ingredientes reales", "Sin conservantes artificiales", "Listas para calentar y compartir"]'::jsonb, 'Yuca y mezcla natural según variedad.', 'Mantener congelado. Cerrar bien el empaque después de abrir.', 'Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.', 'Desayuno, cena ligera o acompañamiento saludable.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-AR-005', 'Yuca + Ajo Asado & Romero', 'Yuca + Ajo Asado & Romero', 'Arepa artesanal de yuca + ajo asado & romero elaborada para calentar, servir y disfrutar en casa.', 'Arepa artesanal de yuca + ajo asado & romero elaborada para calentar, servir y disfrutar en casa.', 'Cocina', 'Arepas', 19, 3.17, '6 Paquete', '680 g (24 oz)', null, 'active', false, 'https://myraices.com/assets/products/arepas/arepa-yuca-ajo-romero.jpg', 5, 6, 113.0, 'g', 0, 0, 'yuca-ajo-asado-and-romero', 'Yuca + Ajo Asado & Romero', 'Arepa artesanal de yuca + ajo asado & romero elaborada para calentar, servir y disfrutar en casa.', '{}'::text[], 'Kitchen', 'Signature Arepas', 'Arepas', 'Paquete', '113 g (4 oz)', '680 g (24 oz)', 'Yuca + Ajo Asado & Romero forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', 'Yuca + Ajo Asado & Romero forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', '["Hechas con raíces e ingredientes reales", "Sin conservantes artificiales", "Listas para calentar y compartir"]'::jsonb, 'Yuca y mezcla natural según variedad.', 'Mantener congelado. Cerrar bien el empaque después de abrir.', 'Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.', 'Desayuno, cena ligera o acompañamiento saludable.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-AR-006', 'Yuca 4 Seeds', 'Yuca 4 Seeds', 'Arepa artesanal de yuca 4 seeds elaborada para calentar, servir y disfrutar en casa.', 'Arepa artesanal de yuca 4 seeds elaborada para calentar, servir y disfrutar en casa.', 'Cocina', 'Arepas', 20, 3.33, '6 Paquete', '680 g (24 oz)', null, 'active', false, 'https://myraices.com/assets/products/arepas/arepa-yuca-4-seeds.jpg', 6, 6, 113.0, 'g', 0, 0, 'yuca-4-seeds', 'Yuca 4 Seeds', 'Arepa artesanal de yuca 4 seeds elaborada para calentar, servir y disfrutar en casa.', '{}'::text[], 'Kitchen', 'Signature Arepas', 'Arepas', 'Paquete', '113 g (4 oz)', '680 g (24 oz)', 'Yuca 4 Seeds forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', 'Yuca 4 Seeds forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', '["Hechas con raíces e ingredientes reales", "Sin conservantes artificiales", "Listas para calentar y compartir"]'::jsonb, 'Yuca y mezcla natural según variedad.', 'Mantener congelado. Cerrar bien el empaque después de abrir.', 'Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.', 'Desayuno, cena ligera o acompañamiento saludable.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-AR-007', 'Batata & Yuca', 'Batata & Yuca', 'Arepa artesanal de batata & yuca elaborada para calentar, servir y disfrutar en casa.', 'Arepa artesanal de batata & yuca elaborada para calentar, servir y disfrutar en casa.', 'Cocina', 'Arepas', 20, 3.33, '6 Paquete', '680 g (24 oz)', null, 'active', false, 'https://myraices.com/assets/products/arepas/arepa-batata-yuca.jpg', 7, 6, 113.0, 'g', 0, 0, 'batata-and-yuca', 'Batata & Yuca', 'Arepa artesanal de batata & yuca elaborada para calentar, servir y disfrutar en casa.', '{}'::text[], 'Kitchen', 'Signature Arepas', 'Arepas', 'Paquete', '113 g (4 oz)', '680 g (24 oz)', 'Batata & Yuca forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', 'Batata & Yuca forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', '["Hechas con raíces e ingredientes reales", "Sin conservantes artificiales", "Listas para calentar y compartir"]'::jsonb, 'Yuca y mezcla natural según variedad.', 'Mantener congelado. Cerrar bien el empaque después de abrir.', 'Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.', 'Desayuno, cena ligera o acompañamiento saludable.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-AR-008', 'Plátano Maduro', 'Plátano Maduro', 'Arepa artesanal de plátano maduro elaborada para calentar, servir y disfrutar en casa.', 'Arepa artesanal de plátano maduro elaborada para calentar, servir y disfrutar en casa.', 'Cocina', 'Arepas', 19, 3.17, '6 Paquete', '680 g (24 oz)', null, 'active', false, 'https://myraices.com/assets/products/arepas/arepa-platano-maduro.jpg', 8, 6, 113.0, 'g', 0, 0, 'platano-maduro', 'Plátano Maduro', 'Arepa artesanal de plátano maduro elaborada para calentar, servir y disfrutar en casa.', '{}'::text[], 'Kitchen', 'Signature Arepas', 'Arepas', 'Paquete', '113 g (4 oz)', '680 g (24 oz)', 'Plátano Maduro forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', 'Plátano Maduro forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.', '["Hechas con raíces e ingredientes reales", "Sin conservantes artificiales", "Listas para calentar y compartir"]'::jsonb, 'Yuca y mezcla natural según variedad.', 'Mantener congelado. Cerrar bien el empaque después de abrir.', 'Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.', 'Desayuno, cena ligera o acompañamiento saludable.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-EM-001', 'Yuca Clásica + Pollo Mechado', 'Yuca Clásica + Pollo Mechado', 'Empanada artesanal yuca clásica + pollo mechado con masa inspirada en raíces naturales y relleno sabroso.', 'Empanada artesanal yuca clásica + pollo mechado con masa inspirada en raíces naturales y relleno sabroso.', 'Cocina', 'Empanadas', 23, 5.75, '4 Paquete', '568 g (20 oz)', null, 'active', false, 'https://myraices.com/assets/products/empanadas/empanada-yuca-pollo.jpg', 9, 4, 142.0, 'g', 0, 0, 'yuca-clasica-pollo-mechado', 'Yuca Clásica + Pollo Mechado', 'Empanada artesanal yuca clásica + pollo mechado con masa inspirada en raíces naturales y relleno sabroso.', '{}'::text[], 'Kitchen', 'Signature Empanadas', 'Empanadas', 'Paquete', '142 g (5 oz)', '568 g (20 oz)', 'Yuca Clásica + Pollo Mechado combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', 'Yuca Clásica + Pollo Mechado combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', '["Masa artesanal", "Rellenos con sabor casero", "Prácticas para air fryer u horno"]'::jsonb, 'Masa de raíz y relleno según variedad.', 'Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.', 'Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.', 'Almuerzo rápido, cena práctica o snack salado.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-EM-002', 'Yuca + Pavo al Romero', 'Yuca + Pavo al Romero', 'Empanada artesanal yuca + pavo al romero con masa inspirada en raíces naturales y relleno sabroso.', 'Empanada artesanal yuca + pavo al romero con masa inspirada en raíces naturales y relleno sabroso.', 'Cocina', 'Empanadas', 23, 5.75, '4 Paquete', '568 g (20 oz)', null, 'active', false, 'https://myraices.com/assets/products/empanadas/empanada-yuca-pavo-romero.jpg', 10, 4, 142.0, 'g', 0, 0, 'yuca-pavo-al-romero', 'Yuca + Pavo al Romero', 'Empanada artesanal yuca + pavo al romero con masa inspirada en raíces naturales y relleno sabroso.', '{}'::text[], 'Kitchen', 'Signature Empanadas', 'Empanadas', 'Paquete', '142 g (5 oz)', '568 g (20 oz)', 'Yuca + Pavo al Romero combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', 'Yuca + Pavo al Romero combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', '["Masa artesanal", "Rellenos con sabor casero", "Prácticas para air fryer u horno"]'::jsonb, 'Masa de raíz y relleno según variedad.', 'Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.', 'Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.', 'Almuerzo rápido, cena práctica o snack salado.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-EM-003', 'Plátano Maduro + Pollo', 'Plátano Maduro + Pollo', 'Empanada artesanal plátano maduro + pollo con masa inspirada en raíces naturales y relleno sabroso.', 'Empanada artesanal plátano maduro + pollo con masa inspirada en raíces naturales y relleno sabroso.', 'Cocina', 'Empanadas', 23, 5.75, '4 Paquete', '568 g (20 oz)', null, 'active', false, 'https://myraices.com/assets/products/empanadas/empanada-platano-pollo.jpg', 11, 4, 142.0, 'g', 0, 0, 'platano-maduro-pollo', 'Plátano Maduro + Pollo', 'Empanada artesanal plátano maduro + pollo con masa inspirada en raíces naturales y relleno sabroso.', '{}'::text[], 'Kitchen', 'Signature Empanadas', 'Empanadas', 'Paquete', '142 g (5 oz)', '568 g (20 oz)', 'Plátano Maduro + Pollo combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', 'Plátano Maduro + Pollo combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', '["Masa artesanal", "Rellenos con sabor casero", "Prácticas para air fryer u horno"]'::jsonb, 'Masa de raíz y relleno según variedad.', 'Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.', 'Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.', 'Almuerzo rápido, cena práctica o snack salado.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-EM-004', 'Yuca + Remolacha + Carne Mechada', 'Yuca + Remolacha + Carne Mechada', 'Empanada artesanal yuca + remolacha + carne mechada con masa inspirada en raíces naturales y relleno sabroso.', 'Empanada artesanal yuca + remolacha + carne mechada con masa inspirada en raíces naturales y relleno sabroso.', 'Cocina', 'Empanadas', 23, 5.75, '4 Paquete', '568 g (20 oz)', null, 'active', false, 'https://myraices.com/assets/products/empanadas/empanada-yuca-remolacha-carne.jpg', 12, 4, 142.0, 'g', 0, 0, 'yuca-remolacha-carne-mechada', 'Yuca + Remolacha + Carne Mechada', 'Empanada artesanal yuca + remolacha + carne mechada con masa inspirada en raíces naturales y relleno sabroso.', '{}'::text[], 'Kitchen', 'Signature Empanadas', 'Empanadas', 'Paquete', '142 g (5 oz)', '568 g (20 oz)', 'Yuca + Remolacha + Carne Mechada combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', 'Yuca + Remolacha + Carne Mechada combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', '["Masa artesanal", "Rellenos con sabor casero", "Prácticas para air fryer u horno"]'::jsonb, 'Masa de raíz y relleno según variedad.', 'Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.', 'Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.', 'Almuerzo rápido, cena práctica o snack salado.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-EM-005', 'Yuca + Cúrcuma + Pollo Curry', 'Yuca + Cúrcuma + Pollo Curry', 'Empanada artesanal yuca + cúrcuma + pollo curry con masa inspirada en raíces naturales y relleno sabroso.', 'Empanada artesanal yuca + cúrcuma + pollo curry con masa inspirada en raíces naturales y relleno sabroso.', 'Cocina', 'Empanadas', 23, 5.75, '4 Paquete', '568 g (20 oz)', null, 'active', false, 'https://myraices.com/assets/products/empanadas/empanada-yuca-curcuma-pollo.jpg', 13, 4, 142.0, 'g', 0, 0, 'yuca-curcuma-pollo-curry', 'Yuca + Cúrcuma + Pollo Curry', 'Empanada artesanal yuca + cúrcuma + pollo curry con masa inspirada en raíces naturales y relleno sabroso.', '{}'::text[], 'Kitchen', 'Signature Empanadas', 'Empanadas', 'Paquete', '142 g (5 oz)', '568 g (20 oz)', 'Yuca + Cúrcuma + Pollo Curry combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', 'Yuca + Cúrcuma + Pollo Curry combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', '["Masa artesanal", "Rellenos con sabor casero", "Prácticas para air fryer u horno"]'::jsonb, 'Masa de raíz y relleno según variedad.', 'Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.', 'Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.', 'Almuerzo rápido, cena práctica o snack salado.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-EM-006', 'Yuca + Espinaca + Queso', 'Yuca + Espinaca + Queso', 'Empanada artesanal yuca + espinaca + queso con masa inspirada en raíces naturales y relleno sabroso.', 'Empanada artesanal yuca + espinaca + queso con masa inspirada en raíces naturales y relleno sabroso.', 'Cocina', 'Empanadas', 23, 5.75, '4 Paquete', '568 g (20 oz)', null, 'active', false, 'https://myraices.com/assets/products/empanadas/empanada-yuca-espinaca-queso.jpg', 14, 4, 142.0, 'g', 0, 0, 'yuca-espinaca-queso', 'Yuca + Espinaca + Queso', 'Empanada artesanal yuca + espinaca + queso con masa inspirada en raíces naturales y relleno sabroso.', '{}'::text[], 'Kitchen', 'Signature Empanadas', 'Empanadas', 'Paquete', '142 g (5 oz)', '568 g (20 oz)', 'Yuca + Espinaca + Queso combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', 'Yuca + Espinaca + Queso combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', '["Masa artesanal", "Rellenos con sabor casero", "Prácticas para air fryer u horno"]'::jsonb, 'Masa de raíz y relleno según variedad.', 'Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.', 'Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.', 'Almuerzo rápido, cena práctica o snack salado.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-EM-007', 'Yuca 4 Seeds + Pavo', 'Yuca 4 Seeds + Pavo', 'Empanada artesanal yuca 4 seeds + pavo con masa inspirada en raíces naturales y relleno sabroso.', 'Empanada artesanal yuca 4 seeds + pavo con masa inspirada en raíces naturales y relleno sabroso.', 'Cocina', 'Empanadas', 23, 5.75, '4 Paquete', '568 g (20 oz)', null, 'active', false, 'https://myraices.com/assets/products/empanadas/empanada-yuca-4-seeds-pavo.jpg', 15, 4, 142.0, 'g', 0, 0, 'yuca-4-seeds-pavo', 'Yuca 4 Seeds + Pavo', 'Empanada artesanal yuca 4 seeds + pavo con masa inspirada en raíces naturales y relleno sabroso.', '{}'::text[], 'Kitchen', 'Signature Empanadas', 'Empanadas', 'Paquete', '142 g (5 oz)', '568 g (20 oz)', 'Yuca 4 Seeds + Pavo combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', 'Yuca 4 Seeds + Pavo combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.', '["Masa artesanal", "Rellenos con sabor casero", "Prácticas para air fryer u horno"]'::jsonb, 'Masa de raíz y relleno según variedad.', 'Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.', 'Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.', 'Almuerzo rápido, cena práctica o snack salado.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-PC-001', 'Pollo al Romero & Limón', 'Pollo al Romero & Limón', 'Proteína artesanal pollo al romero & limón, cocinada lentamente y lista para disfrutar.', 'Proteína artesanal pollo al romero & limón, cocinada lentamente y lista para disfrutar.', 'Cocina', 'Proteínas', 16, 16.0, '1 Lbs', '454 g (16 oz)', null, 'active', false, 'https://myraices.com/assets/products/proteinas/proteina-pollo-romero-limon.jpg', 16, 1, 454.0, 'g', 0, 0, 'pollo-al-romero-and-limon', 'Pollo al Romero & Limón', 'Proteína artesanal pollo al romero & limón, cocinada lentamente y lista para disfrutar.', '{}'::text[], 'Kitchen', 'Protein Craft Collection', 'Proteínas', 'Lbs', '454 g (16 oz)', '454 g (16 oz)', 'Pollo al Romero & Limón pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.', 'Pollo al Romero & Limón pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.', '["Alta en proteína", "Cocinada lentamente", "Lista para combinar con arepas, bowls o ensaladas"]'::jsonb, 'Proteína principal, hierbas y condimentos naturales según variedad.', 'Mantener refrigerado o congelado según fecha de producción. Consumir después de calentar completamente.', 'Calentar en sartén, microondas u horno hasta alcanzar temperatura adecuada.', 'Meal prep, bowls, cenas rápidas o complemento de platos principales.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-PC-002', 'Carne Mechada Signature', 'Carne Mechada Signature', 'Proteína artesanal carne mechada signature, cocinada lentamente y lista para disfrutar.', 'Proteína artesanal carne mechada signature, cocinada lentamente y lista para disfrutar.', 'Cocina', 'Proteínas', 19, 19.0, '1 Lbs', '454 g (16 oz)', null, 'active', false, 'https://myraices.com/assets/products/proteinas/proteina-carne-mechada.jpg', 17, 1, 454.0, 'g', 0, 0, 'carne-mechada-signature', 'Carne Mechada Signature', 'Proteína artesanal carne mechada signature, cocinada lentamente y lista para disfrutar.', '{}'::text[], 'Kitchen', 'Protein Craft Collection', 'Proteínas', 'Lbs', '454 g (16 oz)', '454 g (16 oz)', 'Carne Mechada Signature pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.', 'Carne Mechada Signature pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.', '["Alta en proteína", "Cocinada lentamente", "Lista para combinar con arepas, bowls o ensaladas"]'::jsonb, 'Proteína principal, hierbas y condimentos naturales según variedad.', 'Mantener refrigerado o congelado según fecha de producción. Consumir después de calentar completamente.', 'Calentar en sartén, microondas u horno hasta alcanzar temperatura adecuada.', 'Meal prep, bowls, cenas rápidas o complemento de platos principales.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-PC-003', 'Pavo Molido Mediterráneo', 'Pavo Molido Mediterráneo', 'Proteína artesanal pavo molido mediterráneo, cocinada lentamente y lista para disfrutar.', 'Proteína artesanal pavo molido mediterráneo, cocinada lentamente y lista para disfrutar.', 'Cocina', 'Proteínas', 17, 17.0, '1 Lbs', '454 g (16 oz)', null, 'active', false, 'https://myraices.com/assets/products/proteinas/proteina-pavo-mediterraneo.jpg', 18, 1, 454.0, 'g', 0, 0, 'pavo-molido-mediterraneo', 'Pavo Molido Mediterráneo', 'Proteína artesanal pavo molido mediterráneo, cocinada lentamente y lista para disfrutar.', '{}'::text[], 'Kitchen', 'Protein Craft Collection', 'Proteínas', 'Lbs', '454 g (16 oz)', '454 g (16 oz)', 'Pavo Molido Mediterráneo pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.', 'Pavo Molido Mediterráneo pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.', '["Alta en proteína", "Cocinada lentamente", "Lista para combinar con arepas, bowls o ensaladas"]'::jsonb, 'Proteína principal, hierbas y condimentos naturales según variedad.', 'Mantener refrigerado o congelado según fecha de producción. Consumir después de calentar completamente.', 'Calentar en sartén, microondas u horno hasta alcanzar temperatura adecuada.', 'Meal prep, bowls, cenas rápidas o complemento de platos principales.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-PC-004', 'Pescado al Limón & Hierbas', 'Pescado al Limón & Hierbas', 'Proteína artesanal pescado al limón & hierbas, cocinada lentamente y lista para disfrutar.', 'Proteína artesanal pescado al limón & hierbas, cocinada lentamente y lista para disfrutar.', 'Cocina', 'Proteínas', 20, 20.0, '1 Lbs', '454 g (16 oz)', null, 'active', false, 'https://myraices.com/assets/products/proteinas/proteina-pescado-limon-hierbas.jpg', 19, 1, 454.0, 'g', 0, 0, 'pescado-al-limon-and-hierbas', 'Pescado al Limón & Hierbas', 'Proteína artesanal pescado al limón & hierbas, cocinada lentamente y lista para disfrutar.', '{}'::text[], 'Kitchen', 'Protein Craft Collection', 'Proteínas', 'Lbs', '454 g (16 oz)', '454 g (16 oz)', 'Pescado al Limón & Hierbas pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.', 'Pescado al Limón & Hierbas pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.', '["Alta en proteína", "Cocinada lentamente", "Lista para combinar con arepas, bowls o ensaladas"]'::jsonb, 'Proteína principal, hierbas y condimentos naturales según variedad.', 'Mantener refrigerado o congelado según fecha de producción. Consumir después de calentar completamente.', 'Calentar en sartén, microondas u horno hasta alcanzar temperatura adecuada.', 'Meal prep, bowls, cenas rápidas o complemento de platos principales.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-PC-005', 'Cerdo al Ajo Asado & Tomillo', 'Cerdo al Ajo Asado & Tomillo', 'Proteína artesanal cerdo al ajo asado & tomillo, cocinada lentamente y lista para disfrutar.', 'Proteína artesanal cerdo al ajo asado & tomillo, cocinada lentamente y lista para disfrutar.', 'Cocina', 'Proteínas', 17, 17.0, '1 Lbs', '454 g (16 oz)', null, 'active', false, 'https://myraices.com/assets/products/proteinas/proteina-cerdo-ajo-tomillo.jpg', 20, 1, 454.0, 'g', 0, 0, 'cerdo-al-ajo-asado-and-tomillo', 'Cerdo al Ajo Asado & Tomillo', 'Proteína artesanal cerdo al ajo asado & tomillo, cocinada lentamente y lista para disfrutar.', '{}'::text[], 'Kitchen', 'Protein Craft Collection', 'Proteínas', 'Lbs', '454 g (16 oz)', '454 g (16 oz)', 'Cerdo al Ajo Asado & Tomillo pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.', 'Cerdo al Ajo Asado & Tomillo pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.', '["Alta en proteína", "Cocinada lentamente", "Lista para combinar con arepas, bowls o ensaladas"]'::jsonb, 'Proteína principal, hierbas y condimentos naturales según variedad.', 'Mantener refrigerado o congelado según fecha de producción. Consumir después de calentar completamente.', 'Calentar en sartén, microondas u horno hasta alcanzar temperatura adecuada.', 'Meal prep, bowls, cenas rápidas o complemento de platos principales.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-TM-001', 'Slim & Drain', 'Slim & Drain', 'Mezcla herbal Slim & Drain creada para acompañar un momento específico de tu día.', 'Mezcla herbal Slim & Drain creada para acompañar un momento específico de tu día.', 'Herbal', 'Herbal', 19, 19.0, '1 Unidad', '60 g (2.11 oz)', null, 'active', false, 'https://myraices.com/assets/products/herbal/te-slim-drain.jpg', 21, 1, 60.0, 'g', 0, 0, 'slim-and-drain', 'Slim & Drain', 'Mezcla herbal Slim & Drain creada para acompañar un momento específico de tu día.', '{}'::text[], 'Herbal', 'Three Moments', 'Herbal', 'Unidad', '60 g (2.11 oz)', '60 g (2.11 oz)', 'Slim & Drain forma parte del universo Herbal de Raíces: infusiones pensadas como pequeños rituales diarios para reconectar con el cuerpo, la pausa y la intención.', 'Slim & Drain forma parte del universo Herbal de Raíces: infusiones pensadas como pequeños rituales diarios para reconectar con el cuerpo, la pausa y la intención.', '["Mezcla herbal natural", "Ritual diario de bienestar", "Empaque pensado para regalar o disfrutar"]'::jsonb, 'Mezcla de hierbas e ingredientes botánicos.', 'Conservar en lugar fresco y seco. Mantener cerrado después de abrir.', 'Infusionar en agua caliente de 5 a 8 minutos. Ajustar intensidad al gusto.', 'Mañana, tarde o noche según el ritual elegido.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-TM-002', 'Golden Fit', 'Golden Fit', 'Mezcla herbal Golden Fit creada para acompañar un momento específico de tu día.', 'Mezcla herbal Golden Fit creada para acompañar un momento específico de tu día.', 'Herbal', 'Herbal', 20, 20.0, '1 Unidad', '60 g (2.11 oz)', null, 'active', false, 'https://myraices.com/assets/products/herbal/te-golden-fit.jpg', 22, 1, 60.0, 'g', 0, 0, 'golden-fit', 'Golden Fit', 'Mezcla herbal Golden Fit creada para acompañar un momento específico de tu día.', '{}'::text[], 'Herbal', 'Three Moments', 'Herbal', 'Unidad', '60 g (2.11 oz)', '60 g (2.11 oz)', 'Golden Fit forma parte del universo Herbal de Raíces: infusiones pensadas como pequeños rituales diarios para reconectar con el cuerpo, la pausa y la intención.', 'Golden Fit forma parte del universo Herbal de Raíces: infusiones pensadas como pequeños rituales diarios para reconectar con el cuerpo, la pausa y la intención.', '["Mezcla herbal natural", "Ritual diario de bienestar", "Empaque pensado para regalar o disfrutar"]'::jsonb, 'Mezcla de hierbas e ingredientes botánicos.', 'Conservar en lugar fresco y seco. Mantener cerrado después de abrir.', 'Infusionar en agua caliente de 5 a 8 minutos. Ajustar intensidad al gusto.', 'Mañana, tarde o noche según el ritual elegido.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-TM-003', 'Dream & Calm', 'Dream & Calm', 'Mezcla herbal Dream & Calm creada para acompañar un momento específico de tu día.', 'Mezcla herbal Dream & Calm creada para acompañar un momento específico de tu día.', 'Herbal', 'Herbal', 19, 19.0, '1 Unidad', '60 g (2.11 oz)', null, 'active', false, 'https://myraices.com/assets/products/herbal/te-dream-calm.jpg', 23, 1, 60.0, 'g', 0, 0, 'dream-and-calm', 'Dream & Calm', 'Mezcla herbal Dream & Calm creada para acompañar un momento específico de tu día.', '{}'::text[], 'Herbal', 'Three Moments', 'Herbal', 'Unidad', '60 g (2.11 oz)', '60 g (2.11 oz)', 'Dream & Calm forma parte del universo Herbal de Raíces: infusiones pensadas como pequeños rituales diarios para reconectar con el cuerpo, la pausa y la intención.', 'Dream & Calm forma parte del universo Herbal de Raíces: infusiones pensadas como pequeños rituales diarios para reconectar con el cuerpo, la pausa y la intención.', '["Mezcla herbal natural", "Ritual diario de bienestar", "Empaque pensado para regalar o disfrutar"]'::jsonb, 'Mezcla de hierbas e ingredientes botánicos.', 'Conservar en lugar fresco y seco. Mantener cerrado después de abrir.', 'Infusionar en agua caliente de 5 a 8 minutos. Ajustar intensidad al gusto.', 'Mañana, tarde o noche según el ritual elegido.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-TM-004', 'Gut Harmony', 'Gut Harmony', 'Mezcla herbal Gut Harmony creada para acompañar la digestión ligera y el bienestar desde adentro.', 'Mezcla herbal Gut Harmony creada para acompañar la digestión ligera y el bienestar desde adentro.', 'Herbal', 'Herbal', 19, 19.0, '1 Unidad', '60 g (2.11 oz)', null, 'active', false, 'https://myraices.com/assets/products/herbal/te-gut-harmony.jpg', 24, 1, 60.0, 'g', 0, 0, 'gut-harmony', 'Gut Harmony', 'Mezcla herbal Gut Harmony creada para acompañar la digestión ligera y el bienestar desde adentro.', '{}'::text[], 'Herbal', 'Three Moments', 'Herbal', 'Unidad', '60 g (2.11 oz)', '60 g (2.11 oz)', 'Gut Harmony forma parte del universo Herbal de Raíces: una infusión pensada para acompañar momentos de equilibrio, ligereza y conexión con el cuerpo.', 'Gut Harmony forma parte del universo Herbal de Raíces: una infusión pensada para acompañar momentos de equilibrio, ligereza y conexión con el cuerpo.', '["Mezcla herbal natural", "Apoya un ritual digestivo ligero", "Ideal para después de comer o cerrar el día"]'::jsonb, 'Mezcla herbal con ingredientes botánicos como menta, jengibre y notas cítricas según formulación.', 'Conservar en lugar fresco y seco. Mantener cerrado después de abrir.', 'Infusionar en agua caliente de 5 a 8 minutos. Ajustar intensidad al gusto.', 'Después de comer, pausa de tarde o ritual de bienestar digestivo.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-RC-001', 'Ritual Collection', 'Ritual Collection', 'Colección completa con los tres tés insignia de Raíces para acompañar tus momentos de energía, equilibrio y calma.', 'Colección completa con los tres tés insignia de Raíces para acompañar tus momentos de energía, equilibrio y calma.', 'Herbal', 'Herbal', 30, 10.0, '3 Caja', '60 g (2.11 oz)', null, 'active', false, 'https://myraices.com/assets/products/herbal/herbal-ritual-collection.jpg', 25, 3, 60.0, 'g', 0, 0, 'ritual-collection', 'Ritual Collection', 'Colección completa con los tres tés insignia de Raíces para acompañar tus momentos de energía, equilibrio y calma.', '{}'::text[], 'Herbal', 'Ritual Collection', 'Herbal', 'Caja', '60 g (2.11 oz)', '60 g (2.11 oz)', 'Ritual Collection reúne Slim & Drain, Golden Fit y Dream & Calm en una experiencia herbal completa para crear constancia, presencia y pequeños rituales diarios.', 'Ritual Collection reúne Slim & Drain, Golden Fit y Dream & Calm en una experiencia herbal completa para crear constancia, presencia y pequeños rituales diarios.', '["Incluye los tres tés Raíces", "Ideal para regalar o comenzar tu ritual", "Una experiencia completa de bienestar herbal"]'::jsonb, 'Slim & Drain, Golden Fit y Dream & Calm.', 'Conservar en lugar fresco y seco. Mantener cerrado después de abrir.', 'Elige el té según el momento del día. Infusionar de 5 a 8 minutos y disfrutar con intención.', 'Para acompañar mañana, tarde y noche con un ritual diferente.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-RB-001', 'Ritual Box', 'Ritual Box', 'Caja ritual premium con té a elección, mug Raíces, difusor dorado y tarjeta de preparación.', 'Caja ritual premium con té a elección, mug Raíces, difusor dorado y tarjeta de preparación.', 'Herbal', 'Herbal', 50, 50.0, '1 Caja', null, null, 'active', false, 'https://myraices.com/assets/products/herbal/herbal-ritual-box-dream-calm.jpg', 26, 1, null, 'g', 0, 0, 'ritual-box', 'Ritual Box', 'Caja ritual premium con té a elección, mug Raíces, difusor dorado y tarjeta de preparación.', '{}'::text[], 'Herbal', 'Ritual Box', 'Herbal', 'Caja', '', '', 'Ritual Box es una experiencia completa para regalar o regalarte una pausa: elige tu té Raíces favorito y recibe una caja premium con mug, difusor y tarjeta ritual.', 'Ritual Box es una experiencia completa para regalar o regalarte una pausa: elige tu té Raíces favorito y recibe una caja premium con mug, difusor y tarjeta ritual.', '["Incluye té a elección", "Incluye mug, difusor y tarjeta ritual", "Una experiencia lista para regalar"]'::jsonb, 'Caja premium con un té Raíces a elección, mug, difusor dorado y tarjeta ritual.', 'Conservar el té en lugar fresco y seco. Cuidar mug y difusor según material.', 'Elige tu té, prepara la infusión con el difusor y sigue la tarjeta ritual incluida.', 'Regalo, pausa nocturna, ritual de mañana o momento de conexión.', 'Completa tu ritual', '[{"name": "Dream & Calm", "image": "assets/products/herbal/herbal-ritual-box-dream-calm.jpg"}, {"name": "Golden Fit", "image": "assets/products/herbal/herbal-ritual-box-golden-fit.jpg"}, {"name": "Slim & Drain", "image": "assets/products/herbal/herbal-ritual-box-slim-drain.jpg"}]'::jsonb, null),
  ('RA-DE-001', 'Sweet Potato Cake', 'Sweet Potato Cake', 'Postre artesanal Sweet Potato Cake, hecho para disfrutar despacio y con ingredientes reales.', 'Postre artesanal Sweet Potato Cake, hecho para disfrutar despacio y con ingredientes reales.', 'Dulces', 'Postres', 12, 12.0, '1 Unidad', '340 g (12 oz)', null, 'active', false, 'https://myraices.com/assets/products/desserts/cake-sweet-potato.jpg', 27, 1, 340.0, 'g', 0, 0, 'sweet-potato-cake', 'Sweet Potato Cake', 'Postre artesanal Sweet Potato Cake, hecho para disfrutar despacio y con ingredientes reales.', '{}'::text[], 'Desserts', 'Signature Desserts', 'Postres', 'Unidad', '340 g (12 oz)', '340 g (12 oz)', 'Sweet Potato Cake representa la línea Signature Desserts de Raíces: postres con personalidad, porciones generosas y una visión más consciente de lo dulce.', 'Sweet Potato Cake representa la línea Signature Desserts de Raíces: postres con personalidad, porciones generosas y una visión más consciente de lo dulce.', '["Hecho con ingredientes reales", "Porción lista para disfrutar", "Lo dulce también puede nutrir"]'::jsonb, 'Ingredientes naturales según variedad.', 'Mantener refrigerado. Consumir dentro del periodo indicado en la etiqueta.', 'Servir frío o dejar reposar unos minutos antes de disfrutar.', 'Merienda, postre o detalle especial para compartir.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-DE-002', 'Beet Velvet Cake', 'Beet Velvet Cake', 'Postre artesanal Beet Velvet Cake, hecho para disfrutar despacio y con ingredientes reales.', 'Postre artesanal Beet Velvet Cake, hecho para disfrutar despacio y con ingredientes reales.', 'Dulces', 'Postres', 13, 13.0, '1 Unidad', '340 g (12 oz)', null, 'active', false, 'https://myraices.com/assets/products/desserts/cake-beet-velvet.jpg', 28, 1, 340.0, 'g', 0, 0, 'beet-velvet-cake', 'Beet Velvet Cake', 'Postre artesanal Beet Velvet Cake, hecho para disfrutar despacio y con ingredientes reales.', '{}'::text[], 'Desserts', 'Signature Desserts', 'Postres', 'Unidad', '340 g (12 oz)', '340 g (12 oz)', 'Beet Velvet Cake representa la línea Signature Desserts de Raíces: postres con personalidad, porciones generosas y una visión más consciente de lo dulce.', 'Beet Velvet Cake representa la línea Signature Desserts de Raíces: postres con personalidad, porciones generosas y una visión más consciente de lo dulce.', '["Hecho con ingredientes reales", "Porción lista para disfrutar", "Lo dulce también puede nutrir"]'::jsonb, 'Ingredientes naturales según variedad.', 'Mantener refrigerado. Consumir dentro del periodo indicado en la etiqueta.', 'Servir frío o dejar reposar unos minutos antes de disfrutar.', 'Merienda, postre o detalle especial para compartir.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-DE-003', 'Carrot Cake', 'Carrot Cake', 'Postre artesanal Carrot Cake, hecho para disfrutar despacio y con ingredientes reales.', 'Postre artesanal Carrot Cake, hecho para disfrutar despacio y con ingredientes reales.', 'Dulces', 'Postres', 12, 12.0, '1 Unidad', '340 g (12 oz)', null, 'active', false, 'https://myraices.com/assets/products/desserts/cake-carrot.jpg', 29, 1, 340.0, 'g', 0, 0, 'carrot-cake', 'Carrot Cake', 'Postre artesanal Carrot Cake, hecho para disfrutar despacio y con ingredientes reales.', '{}'::text[], 'Desserts', 'Signature Desserts', 'Postres', 'Unidad', '340 g (12 oz)', '340 g (12 oz)', 'Carrot Cake representa la línea Signature Desserts de Raíces: postres con personalidad, porciones generosas y una visión más consciente de lo dulce.', 'Carrot Cake representa la línea Signature Desserts de Raíces: postres con personalidad, porciones generosas y una visión más consciente de lo dulce.', '["Hecho con ingredientes reales", "Porción lista para disfrutar", "Lo dulce también puede nutrir"]'::jsonb, 'Ingredientes naturales según variedad.', 'Mantener refrigerado. Consumir dentro del periodo indicado en la etiqueta.', 'Servir frío o dejar reposar unos minutos antes de disfrutar.', 'Merienda, postre o detalle especial para compartir.', 'Combina con otros productos Raíces', '[]'::jsonb, null),
  ('RA-HM-001', 'Signature Teapot', 'Signature Teapot', 'Tetera de vidrio Raíces con infusor integrado para preparar tu ritual de té con elegancia.', 'Tetera de vidrio Raíces con infusor integrado para preparar tu ritual de té con elegancia.', 'Home', 'Home', 35, 35.0, '1 Unidad', null, null, 'active', false, 'https://myraices.com/assets/products/home/home-signature-teapot-round.jpg', 30, 1, null, 'g', 0, 0, 'signature-teapot', 'Signature Teapot', 'Tetera de vidrio Raíces con infusor integrado para preparar tu ritual de té con elegancia.', '{}'::text[], 'Home', 'Home Rituals', 'Home', 'Unidad', '', '', 'Signature Teapot pertenece a Home Rituals: una tetera de vidrio diseñada para preparar infusiones con calma, intención y una presencia visual limpia en la mesa.', 'Signature Teapot pertenece a Home Rituals: una tetera de vidrio diseñada para preparar infusiones con calma, intención y una presencia visual limpia en la mesa.', '["Vidrio transparente para apreciar la infusión", "Infusor integrado", "Ideal para servir y compartir"]'::jsonb, 'Vidrio, acero inoxidable y tapa de bambú según modelo.', 'Lavar y cuidar según material. Evitar golpes o cambios bruscos de temperatura si aplica.', 'Añade tu té favorito, vierte agua caliente y deja infusionar según el tipo de mezcla.', 'Rituales de té en casa, sobremesa o pausa consciente.', 'Completa tu ritual', '[{"name": "teapot-round", "labelEs": "Redonda", "labelEn": "Round Teapot", "image": "assets/products/home/home-signature-teapot-round.jpg"}, {"name": "teapot-square", "labelEs": "Cuadrada", "labelEn": "Square Teapot", "image": "assets/products/home/home-signature-teapot-square.jpg"}]'::jsonb, null),
  ('RA-HM-006', 'Infusor Cup', 'Infusor Cup', 'Taza infusora con tapa de bambú e infusor integrado para preparar tu té en una sola pieza.', 'Taza infusora con tapa de bambú e infusor integrado para preparar tu té en una sola pieza.', 'Home', 'Home', 25, 25.0, '1 Unidad', null, null, 'active', false, 'https://myraices.com/assets/products/home/home-infusor-cup.jpg', 31, 1, null, 'g', 0, 0, 'infusor-cup', 'Infusor Cup', 'Taza infusora con tapa de bambú e infusor integrado para preparar tu té en una sola pieza.', '{}'::text[], 'Home', 'Home Rituals', 'Home', 'Unidad', '', '', 'Infusor Cup une taza, infusor y tapa en un solo objeto funcional para preparar tus mezclas Raíces de forma práctica, limpia y elegante.', 'Infusor Cup une taza, infusor y tapa en un solo objeto funcional para preparar tus mezclas Raíces de forma práctica, limpia y elegante.', '["Taza e infusor en una sola pieza", "Tapa de bambú", "Ideal para rituales diarios"]'::jsonb, 'Vidrio, infusor metálico y tapa de bambú según modelo.', 'Lavar y cuidar según material. Evitar golpes o cambios bruscos de temperatura.', 'Añade tu mezcla al infusor, vierte agua caliente, tapa y deja reposar.', 'Ritual diario en casa, lectura, trabajo o pausa de bienestar.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-HM-002', 'Travel Infuser', 'Travel Infuser', 'Botella infusora de viaje para llevar tus tés e infusiones durante el día.', 'Botella infusora de viaje para llevar tus tés e infusiones durante el día.', 'Home', 'Home', 23, 23.0, '1 Unidad', null, null, 'active', false, 'https://myraices.com/assets/products/home/home-travel-infuser.jpg', 32, 1, null, 'g', 0, 0, 'travel-infuser', 'Travel Infuser', 'Botella infusora de viaje para llevar tus tés e infusiones durante el día.', '{}'::text[], 'Home', 'Home Rituals', 'Home', 'Unidad', '', '', 'Travel Infuser acompaña tus rituales fuera de casa: una botella práctica con infusor integrado para preparar o llevar tus mezclas favoritas.', 'Travel Infuser acompaña tus rituales fuera de casa: una botella práctica con infusor integrado para preparar o llevar tus mezclas favoritas.', '["Práctico para llevar", "Infusor integrado", "Acompaña tu rutina diaria"]'::jsonb, 'Vidrio y tapa de bambú según modelo.', 'Lavar y cuidar según material. Evitar golpes o cambios bruscos de temperatura si aplica.', 'Coloca la mezcla en el infusor, añade agua y deja reposar según el té elegido.', 'Rutina de trabajo, viajes cortos o rituales durante el día.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-HM-003', 'Infusor Individual', 'Infusor Individual', 'Infusor individual para preparar una taza de té de forma sencilla y delicada.', 'Infusor individual para preparar una taza de té de forma sencilla y delicada.', 'Home', 'Home', 15, 15.0, '1 Unidad', null, null, 'active', false, 'https://myraices.com/assets/products/home/home-infusor-individual.jpg', 33, 1, null, 'g', 0, 0, 'infusor-individual', 'Infusor Individual', 'Infusor individual para preparar una taza de té de forma sencilla y delicada.', '{}'::text[], 'Home', 'Home Rituals', 'Home', 'Unidad', '', '', 'Infusor Individual es una pieza pequeña y funcional para preparar infusiones sueltas en taza, con un toque artesanal y práctico.', 'Infusor Individual es una pieza pequeña y funcional para preparar infusiones sueltas en taza, con un toque artesanal y práctico.', '["Fácil de usar", "Ideal para una taza", "Ligero y práctico"]'::jsonb, 'Acero inoxidable y detalle decorativo según modelo.', 'Lavar y cuidar según material. Evitar golpes o cambios bruscos de temperatura si aplica.', 'Añade la mezcla al infusor, sumérgelo en agua caliente y retira al alcanzar la intensidad deseada.', 'Una pausa rápida, una taza nocturna o un detalle para regalar.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-HM-004', 'Mug Cerámico', 'Mug Cerámico', 'Mug cerámico Raíces para acompañar tus infusiones y momentos de calma.', 'Mug cerámico Raíces para acompañar tus infusiones y momentos de calma.', 'Home', 'Home', 19, 19.0, '1 Unidad', null, null, 'active', false, 'https://myraices.com/assets/products/home/home-mug-ceramico.jpg', 34, 1, null, 'g', 0, 0, 'mug-ceramico', 'Mug Cerámico', 'Mug cerámico Raíces para acompañar tus infusiones y momentos de calma.', '{}'::text[], 'Home', 'Home Rituals', 'Home', 'Unidad', '', '', 'Mug Cerámico pertenece a Home Rituals: una taza cálida, simple y elegante para convertir una pausa cotidiana en un pequeño ritual.', 'Mug Cerámico pertenece a Home Rituals: una taza cálida, simple y elegante para convertir una pausa cotidiana en un pequeño ritual.', '["Diseño cálido y atemporal", "Perfecto para infusiones", "Ideal para completar tu Ritual Box"]'::jsonb, 'Cerámica artesanal según modelo.', 'Lavar y cuidar según material. Evitar golpes o cambios bruscos de temperatura si aplica.', 'Servir tu infusión favorita y disfrutar despacio.', 'Ritual de la mañana, pausa de tarde o noche de calma.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-HM-005', 'Taza de Vidrio', 'Taza de Vidrio', 'Taza de vidrio Raíces para disfrutar el color natural de tus infusiones.', 'Taza de vidrio Raíces para disfrutar el color natural de tus infusiones.', 'Home', 'Home', 17, 17.0, '1 Unidad', null, null, 'active', false, 'https://myraices.com/assets/products/home/home-taza-vidrio.jpg', 35, 1, null, 'g', 0, 0, 'taza-de-vidrio', 'Taza de Vidrio', 'Taza de vidrio Raíces para disfrutar el color natural de tus infusiones.', '{}'::text[], 'Home', 'Home Rituals', 'Home', 'Unidad', '', '', 'Taza de Vidrio aporta ligereza y transparencia a tu ritual: una pieza pensada para apreciar el color, aroma y calma de cada infusión.', 'Taza de Vidrio aporta ligereza y transparencia a tu ritual: una pieza pensada para apreciar el color, aroma y calma de cada infusión.', '["Transparente y ligera", "Resalta el color del té", "Elegante para servir"]'::jsonb, 'Vidrio con asa de madera según modelo.', 'Lavar y cuidar según material. Evitar golpes o cambios bruscos de temperatura si aplica.', 'Servir tu té o infusión favorita.', 'Pausas ligeras, sobremesa o rituales compartidos.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-LB-001', 'Volver a lo esencial', 'Volver a lo esencial', 'Guía digital Volver a lo esencial para cultivar bienestar desde lo esencial.', 'Guía digital Volver a lo esencial para cultivar bienestar desde lo esencial.', 'Wellness', 'Guías', 20, 20.0, '1 Unidad', null, null, 'active', false, 'https://myraices.com/assets/guide-volver-esencial.jpg', 36, 1, null, 'digital', 0, 0, 'volver-a-lo-esencial', 'Volver a lo esencial', 'Guía digital Volver a lo esencial para cultivar bienestar desde lo esencial.', '{}'::text[], 'Wellness', 'The Library', 'Guías', 'Unidad', '', '', 'Volver a lo esencial forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.', 'Volver a lo esencial forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.', '["Contenido digital práctico", "Diseñado para aplicar en la vida diaria", "Acceso simple desde tu cuenta"]'::jsonb, 'Guía digital en formato ebook/PDF.', 'Producto digital. No requiere conservación física.', 'Descargar, leer y aplicar a tu ritmo.', 'Lectura personal, planificación semanal o acompañamiento de rituales.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-LB-002', '21 días para cultivar tu bienestar', '21 días para cultivar tu bienestar', 'Guía digital 21 días para cultivar tu bienestar para cultivar bienestar desde lo esencial.', 'Guía digital 21 días para cultivar tu bienestar para cultivar bienestar desde lo esencial.', 'Wellness', 'Guías', 30, 30.0, '1 Unidad', null, null, 'active', false, 'https://myraices.com/assets/guide-21-dias.jpg', 37, 1, null, 'digital', 0, 0, '21-dias-para-cultivar-tu-bienestar', '21 días para cultivar tu bienestar', 'Guía digital 21 días para cultivar tu bienestar para cultivar bienestar desde lo esencial.', '{}'::text[], 'Wellness', 'The Library', 'Guías', 'Unidad', '', '', '21 días para cultivar tu bienestar forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.', '21 días para cultivar tu bienestar forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.', '["Contenido digital práctico", "Diseñado para aplicar en la vida diaria", "Acceso simple desde tu cuenta"]'::jsonb, 'Guía digital en formato ebook/PDF.', 'Producto digital. No requiere conservación física.', 'Descargar, leer y aplicar a tu ritmo.', 'Lectura personal, planificación semanal o acompañamiento de rituales.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-LB-003', 'Cocina desde la raíz', 'Cocina desde la raíz', 'Guía digital Cocina desde la raíz para cultivar bienestar desde lo esencial.', 'Guía digital Cocina desde la raíz para cultivar bienestar desde lo esencial.', 'Wellness', 'Guías', 25, 25.0, '1 Unidad', null, null, 'active', false, 'https://myraices.com/assets/guide-cocina-raiz.jpg', 38, 1, null, 'digital', 0, 0, 'cocina-desde-la-raiz', 'Cocina desde la raíz', 'Guía digital Cocina desde la raíz para cultivar bienestar desde lo esencial.', '{}'::text[], 'Wellness', 'The Library', 'Guías', 'Unidad', '', '', 'Cocina desde la raíz forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.', 'Cocina desde la raíz forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.', '["Contenido digital práctico", "Diseñado para aplicar en la vida diaria", "Acceso simple desde tu cuenta"]'::jsonb, 'Guía digital en formato ebook/PDF.', 'Producto digital. No requiere conservación física.', 'Descargar, leer y aplicar a tu ritmo.', 'Lectura personal, planificación semanal o acompañamiento de rituales.', 'Completa tu ritual', '[]'::jsonb, null),
  ('RA-LB-004', 'Rituales', 'Rituales', 'Guía digital Rituales para cultivar bienestar desde lo esencial.', 'Guía digital Rituales para cultivar bienestar desde lo esencial.', 'Wellness', 'Guías', 25, 25.0, '1 Unidad', null, null, 'active', false, 'https://myraices.com/assets/guide-rituales.jpg', 39, 1, null, 'digital', 0, 0, 'rituales', 'Rituales', 'Guía digital Rituales para cultivar bienestar desde lo esencial.', '{}'::text[], 'Wellness', 'The Library', 'Guías', 'Unidad', '', '', 'Rituales forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.', 'Rituales forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.', '["Contenido digital práctico", "Diseñado para aplicar en la vida diaria", "Acceso simple desde tu cuenta"]'::jsonb, 'Guía digital en formato ebook/PDF.', 'Producto digital. No requiere conservación física.', 'Descargar, leer y aplicar a tu ritmo.', 'Lectura personal, planificación semanal o acompañamiento de rituales.', 'Completa tu ritual', '[]'::jsonb, null)

on conflict (sku) do update set
  name_es=excluded.name_es,
  name_en=excluded.name_en,
  description_es=excluded.description_es,
  description_en=excluded.description_en,
  collection=excluded.collection,
  category=excluded.category,
  price=excluded.price,
  unit_price=excluded.unit_price,
  pack_size=excluded.pack_size,
  weight=excluded.weight,
  stock=excluded.stock,
  status=excluded.status,
  featured=excluded.featured,
  image_url=excluded.image_url,
  sort_order=excluded.sort_order,
  units_per_pack=excluded.units_per_pack,
  weight_value=excluded.weight_value,
  weight_unit=excluded.weight_unit,
  minimum_stock=excluded.minimum_stock,
  ideal_stock=excluded.ideal_stock,
  slug=excluded.slug,
  meta_title=excluded.meta_title,
  meta_description=excluded.meta_description,
  tags=excluded.tags,
  display_category=excluded.display_category,
  display_collection=excluded.display_collection,
  subcategory_label=excluded.subcategory_label,
  unit_label=excluded.unit_label,
  unit_weight_label=excluded.unit_weight_label,
  net_weight_label=excluded.net_weight_label,
  long_description_es=excluded.long_description_es,
  long_description_en=excluded.long_description_en,
  benefits=excluded.benefits,
  ingredients_text=excluded.ingredients_text,
  conservation_text=excluded.conservation_text,
  preparation_text=excluded.preparation_text,
  moment_text=excluded.moment_text,
  related_hint=excluded.related_hint,
  variants=excluded.variants,
  taxable=excluded.taxable,
  updated_at=now();

commit;
