(function(){
  'use strict';
  const fallbackImage='/assets/herbal-board.webp';
  window.RaicesBlog={
    lang(){return localStorage.getItem('raices_lang')==='en'?'en':'es';},
    localized(row,key){const lang=this.lang();if(lang==='en')return row[`${key}_en`]||row[key]||'';return row[`${key}_es`]||row[key]||'';},
    image(row){return row.hero_image_url||fallbackImage;},
    date(value){if(!value)return '';return new Intl.DateTimeFormat(this.lang()==='en'?'en-US':'es-US',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value));},
    escape(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));},
    readingTime(row){return row.reading_time_minutes||Math.max(1,Math.ceil(JSON.stringify(row.content_blocks||[]).length/1100));},
    async client(){for(let i=0;i<30;i++){if(window.raicesSupabase)return window.raicesSupabase;await new Promise(r=>setTimeout(r,100));}throw new Error('Supabase unavailable');},
    demoArticles(){return [
      {id:'demo-1',slug:'alimentacion-real-camino-mejor-version',title_es:'Alimentación real: el camino hacia tu mejor versión',title_en:'Real food: the path to your best self',excerpt_es:'Descubre por qué volver a lo esencial en nuestra alimentación puede transformar tu energía, tu cuerpo y tu mente.',excerpt_en:'Discover why returning to essentials can transform your energy, body and mind.',category_name_es:'Nutrición',category_name_en:'Nutrition',hero_image_url:'/assets/arepas-board.webp',author_name:'Equipo My Raíces',published_at:'2026-07-26',featured:true,reading_time_minutes:6,content_blocks:[{type:'paragraph',text_es:'Alimentarnos de forma consciente no significa perseguir la perfección. Significa reconocer los ingredientes, escuchar al cuerpo y construir hábitos sostenibles.'},{type:'heading',level:2,text_es:'Volver a lo esencial'},{type:'paragraph',text_es:'La comida real nos conecta con sabores, texturas y preparaciones que forman parte de nuestra historia.'},{type:'quote',text_es:'El bienestar no comienza con una regla rígida, sino con una decisión cotidiana.'}]},
      {id:'demo-2',slug:'beneficios-tes-herbales',title_es:'Los beneficios de los tés herbales en tu día a día',title_en:'The benefits of herbal teas in your day',excerpt_es:'Una pausa sencilla puede convertirse en un ritual de energía, balance o calma.',excerpt_en:'A simple pause can become a ritual of energy, balance or calm.',category_name_es:'Tés e infusiones',category_name_en:'Teas & infusions',hero_image_url:'/assets/herbal-board.webp',author_name:'Equipo My Raíces',published_at:'2026-07-21',featured:true,reading_time_minutes:4,content_blocks:[{type:'paragraph',text_es:'Una infusión puede ayudarte a crear una pausa consciente en medio del día.'}]},
      {id:'demo-3',slug:'practicas-diarias-reducir-estres',title_es:'5 prácticas diarias para reducir el estrés',title_en:'5 daily practices to reduce stress',excerpt_es:'Pequeños hábitos que pueden ayudarte a recuperar presencia y equilibrio.',excerpt_en:'Small habits that can help you regain presence and balance.',category_name_es:'Bienestar',category_name_en:'Wellness',hero_image_url:'/assets/hero-hand-plant.webp',author_name:'Equipo My Raíces',published_at:'2026-07-18',featured:true,reading_time_minutes:5,content_blocks:[{type:'paragraph',text_es:'Respirar, caminar, descansar y comer con atención son prácticas sencillas que merecen espacio.'}]},
      {id:'demo-4',slug:'curcuma-oro-naturaleza',title_es:'Cúrcuma: el oro de la naturaleza',title_en:'Turmeric: nature’s gold',excerpt_es:'Conoce esta raíz milenaria y algunas formas sencillas de incorporarla a tu rutina.',excerpt_en:'Learn about this ancient root and simple ways to add it to your routine.',category_name_es:'Ingredientes',category_name_en:'Ingredients',hero_image_url:'/assets/arepa-curcuma.webp',author_name:'Equipo My Raíces',published_at:'2026-07-14',reading_time_minutes:5,content_blocks:[{type:'paragraph',text_es:'La cúrcuma aporta color, aroma y una historia culinaria que atraviesa generaciones.'}]},
      {id:'demo-5',slug:'rutinas-vida-consciente',title_es:'Rutinas simples para una vida más consciente',title_en:'Simple routines for a more mindful life',excerpt_es:'Pequeños cambios diarios que generan grandes transformaciones.',excerpt_en:'Small daily changes that create meaningful transformations.',category_name_es:'Estilo de vida',category_name_en:'Lifestyle',hero_image_url:'/assets/home-board.webp',author_name:'Equipo My Raíces',published_at:'2026-07-10',reading_time_minutes:4,content_blocks:[{type:'paragraph',text_es:'La constancia nace cuando una rutina cabe de verdad en nuestra vida.'}]},
      {id:'demo-6',slug:'arepas-yuca-curcuma',title_es:'Arepas de yuca y cúrcuma: sabor que nutre',title_en:'Cassava and turmeric arepas',excerpt_es:'Una forma deliciosa de llevar ingredientes esenciales a la mesa familiar.',excerpt_en:'A delicious way to bring essential ingredients to the family table.',category_name_es:'Recetas',category_name_en:'Recipes',hero_image_url:'/assets/arepa-curcuma.webp',author_name:'Equipo My Raíces',published_at:'2026-07-06',reading_time_minutes:6,content_blocks:[{type:'paragraph',text_es:'La yuca y la cúrcuma crean una combinación de sabor, color y versatilidad.'}]}
    ];},
    async articles(){try{const client=await this.client();const {data,error}=await client.from('blog_articles_public').select('*').order('published_at',{ascending:false});if(error)throw error;return (data||[]).filter(row=>this.lang()!=='en'||Boolean(row.title_en));}catch(e){console.error('No fue posible cargar el Blog desde Supabase:',e.message);return [];}},
    async home(){try{const client=await this.client();const {data,error}=await client.from('blog_home_public').select('*').eq('id','main').maybeSingle();if(error)throw error;return data||null;}catch(e){console.warn('Portada del Blog: usando contenido de respaldo.',e.message);return null;}},
    articleUrl(a){return `/blog/${encodeURIComponent(a.slug)}`;}
  };
})();
