window.RAICES_I18N = {
  es: {
    blog_top_text:'Comida real. Bienestar consciente. Volver a lo esencial.', blog_top_cta:'Únete a la comunidad', blog_view_blog:'Ver el Blog', blog_nav_teas:'Tés e infusiones', blog_nav_home:'Hogar', blog_nav_about:'Sobre Raíces', blog_hero_title:'Bienestar que viene de la raíz', blog_hero_text:'Inspiración, educación y herramientas prácticas para una vida más consciente: desde la alimentación real hasta los hábitos que nutren tu cuerpo, mente y alma.', blog_explore:'Explorar artículos', blog_loading:'Cargando artículos…', blog_email_placeholder:'Tu correo electrónico', blog_back:'← Volver al Blog', blog_loading_article:'Cargando artículo…', blog_share:'Compartir', blog_related:'También puede interesarte', footer_tagline:'La salud comienza desde la raíz.', footer_explore:'Explora', footer_help:'Ayuda', footer_delivery:'Entregas', footer_cancellations:'Cancelaciones', footer_privacy:'Privacidad', footer_terms:'Términos', footer_motto:'Comida real · Bienestar consciente', footer_return:'Volver a lo esencial',
    preopening_text:'Estamos preparando nuestra apertura · Explora la tienda y únete a la lista', preopening_cta:'Avísame', blog_featured:'Artículos destacados', blog_recent:'Artículos recientes', blog_email_title:'Recibe inspiración en tu correo', blog_email_text:'Suscríbete y recibe artículos exclusivos, recetas y tips de bienestar.', blog_subscribe:'Suscribirme', blog_popular:'Artículos populares', nav_home:'Inicio', nav_kitchen:'Cocina', nav_herbal:'Herbal', nav_desserts:'Dulces', nav_home_line:'Home', nav_wellness:'Wellness', nav_about:'Nosotros',
    hero_eyebrow:'Raíces · Marca de bienestar', hero_title:'Nutre tu cuerpo. Vuelve a tus raíces.', hero_text:'Alimentos artesanales, infusiones, objetos para el hogar y guías de bienestar creados para convertir lo cotidiano en ritual.', hero_btn:'Explorar colecciones', hero_story:'Nuestra historia →', trust_real_title:'Ingredientes reales', trust_real_text:'Productos hechos con intención y transparencia.', trust_local_title:'Creado localmente', trust_local_text:'Una marca nacida en Katy para nuestra comunidad.', trust_easy_title:'Bienestar sencillo', trust_easy_text:'Opciones prácticas para tus rituales cotidianos.', trust_delivery_title:'Entrega cercana', trust_delivery_text:'Servicio local pensado con cuidado.', editorial_eyebrow:'Comer bien puede sentirse bien', editorial_title:'Lo esencial, preparado para tu vida real.', editorial_text:'Creamos alimentos y rituales que combinan sabor, bienestar y practicidad para que cuidarte no se convierta en otra tarea.', editorial_cta:'Descubre la colección Cocina →', editorial_stat_products:'productos para descubrir', editorial_stat_collections:'colecciones conectadas',
    collections_eyebrow:'Compra por colección', collections_title:'Una misma raíz. Diferentes rituales.', collections_text:'Explora las líneas principales de Raíces y descubre productos diseñados para nutrir, equilibrar, disfrutar, acompañar y aprender.', sidebar_collections:'Colecciones',
    naturals_title_short:'Naturals', naturals_note:'Próximamente. La línea de suplementos quedará oculta hasta que la marca esté lista para lanzarla con confianza.',
    all_collections:'Todas las colecciones', store:'Tienda Raíces', all_description:'Una tienda organizada por Cocina, Herbal, Dulces, Home y Wellness.', all_filter:'Todas', collection_select_all:'Todas las colecciones', add:'Agregar', cart_empty:'Tu carrito está vacío.',
    about_eyebrow:'Nuestra raíz', about_title:'Más que productos, una forma de vivir.', about_text:'Raíces nace para integrar alimentos reales, rituales herbales, objetos sencillos y conocimiento práctico en una experiencia de bienestar cercana, elegante y sostenible.',
    naturals_eyebrow:'Naturals · Próximamente', naturals_text:'La línea Naturals quedará reservada hasta que Raíces esté lista para lanzar suplementos con la confianza, calidad y claridad que la marca exige.', waitlist_eyebrow:'Lista de espera', waitlist_title:'Recibe noticias del lanzamiento.', waitlist_btn:'Únete a la lista',
    community_eyebrow:'Comunidad Raíces', community_title:'Únete a la comunidad Raíces.', community_text:'Recibe lanzamientos, rituales, recetas y beneficios exclusivos antes que nadie.', newsletter_benefit_1:'Lanzamientos anticipados', newsletter_benefit_2:'Recetas y rituales', newsletter_benefit_3:'Beneficios exclusivos', newsletter_name_label:'Nombre', newsletter_consent:'Acepto recibir comunicaciones de Raíces sobre lanzamientos, productos, recetas y novedades.', newsletter_sending:'Enviando...', newsletter_invalid_email:'Escribe un correo válido.', newsletter_consent_error:'Debes aceptar recibir comunicaciones de Raíces.', newsletter_success:'Gracias por unirte a Raíces. Te enviaremos novedades pronto.', newsletter_error:'No pudimos guardar tu correo. Intenta de nuevo o escríbenos por WhatsApp.', subscribe:'Suscribirme',
    cart_title:'Tu carrito', subtotal:'Subtotal', delivery_label:'Delivery', total_label:'Total', delivery_zip_label:'ZIP Code para delivery', delivery_apply:'Aplicar', delivery_prompt:'Ingresa tu ZIP Code para calcular el delivery.', cart_note:'Los impuestos y el total final se confirmarán durante el pago.', checkout_soon:'Avisarme cuando abran pedidos', waitlist_checkout_eyebrow:'Pedidos próximamente', waitlist_checkout_title:'Estamos preparando la apertura oficial.', waitlist_checkout_text:'Aún no estamos aceptando pedidos porque estamos terminando empaques y detalles de lanzamiento. Déjanos tu correo y te avisaremos cuando abramos la tienda.', waitlist_name_label:'Nombre', waitlist_consent:'Acepto recibir comunicaciones de Raíces sobre lanzamientos, productos y novedades.', waitlist_submit:'Avisarme cuando abran pedidos', help:'¿Necesitas ayuda?',
    signupMarketingConsent:'Quiero recibir novedades, inspiración y ofertas de Raíces por correo. Puedo cancelar la suscripción en cualquier momento.',
    account_eyebrow:'Cuenta Raíces', account_title:'Mi cuenta', account_intro:'Crea tu cuenta o inicia sesión para guardar tus datos, preparar tu carrito y consultar tus pedidos.', login:'Iniciar sesión', signup:'Crear cuenta', enter:'Entrar', forgot:'Olvidé mi contraseña', confirm_email_note:'Revisa tu email para confirmar el registro.', logout:'Cerrar sesión', footer_love:'Hecho con amor · Para ti y para el planeta',
    profile:'Perfil', orders:'Pedidos', addresses:'Direcciones', coming:'Próximamente', view_product:'Ver producto', benefits:'Beneficios', ingredients:'Ingredientes', conservation:'Conservación', preparation:'Preparación', ideal_moment:'Momento ideal', related:'Completa tu ritual', close:'Cerrar', add_to_cart:'Agregar al carrito', sold_out:'Agotado temporalmente', notify_product:'Avisarme', notify_product_title:'Te avisaremos cuando vuelva', notify_product_text:'Déjanos tu correo y te avisaremos cuando este producto vuelva a estar disponible.'
  },
  en: {
    blog_top_text:'Real food. Conscious wellness. Return to what matters.', blog_top_cta:'Join the community', blog_view_blog:'View the Blog', blog_nav_teas:'Teas & infusions', blog_nav_home:'Home', blog_nav_about:'About Raíces', blog_hero_title:'Wellness rooted in what matters', blog_hero_text:'Inspiration, education and practical tools for a more mindful life—from real food to habits that nourish your body, mind and soul.', blog_explore:'Explore articles', blog_loading:'Loading articles…', blog_email_placeholder:'Your email address', blog_back:'← Back to the Blog', blog_loading_article:'Loading article…', blog_share:'Share', blog_related:'You may also like', footer_tagline:'Health begins at the root.', footer_explore:'Explore', footer_help:'Help', footer_delivery:'Delivery', footer_cancellations:'Cancellations', footer_privacy:'Privacy', footer_terms:'Terms', footer_motto:'Real food · Conscious wellness', footer_return:'Return to what matters',
    preopening_text:'We are preparing for our opening · Explore the shop and join the waitlist', preopening_cta:'Notify me', blog_featured:'Featured articles', blog_recent:'Recent articles', blog_email_title:'Get inspiration in your inbox', blog_email_text:'Subscribe for exclusive articles, recipes and wellness tips.', blog_subscribe:'Subscribe', blog_popular:'Popular articles', nav_home:'Home', nav_kitchen:'Kitchen', nav_herbal:'Herbal', nav_desserts:'Desserts', nav_home_line:'Home', nav_wellness:'Wellness', nav_about:'About',
    hero_eyebrow:'Raíces · Wellness Brand', hero_title:'Nourish your body. Return to your roots.', hero_text:'Handcrafted foods, herbal infusions, home objects and wellness guides created to turn everyday moments into meaningful rituals.', hero_btn:'Explore Collections', hero_story:'Our story →', trust_real_title:'Real ingredients', trust_real_text:'Products made with intention and transparency.', trust_local_title:'Locally created', trust_local_text:'A brand born in Katy for our community.', trust_easy_title:'Simple wellness', trust_easy_text:'Practical choices for everyday rituals.', trust_delivery_title:'Thoughtful delivery', trust_delivery_text:'Local service designed with care.', editorial_eyebrow:'Eating well can feel good', editorial_title:'What matters, prepared for real life.', editorial_text:'We create foods and rituals that bring together flavor, wellness and ease, so caring for yourself does not become another task.', editorial_cta:'Discover the Kitchen collection →', editorial_stat_products:'products to discover', editorial_stat_collections:'connected collections',
    collections_eyebrow:'Shop by Collection', collections_title:'One root. Different rituals.', collections_text:'Explore Raíces’ main lines and discover products designed to nourish, balance, enjoy, accompany and learn.', sidebar_collections:'Collections',
    naturals_title_short:'Naturals', naturals_note:'Coming soon. The supplement line will remain hidden until the brand is ready to launch it with confidence.',
    all_collections:'All collections', store:'Raíces Store', all_description:'A store organized by Kitchen, Herbal, Desserts, Home and Wellness.', all_filter:'All', collection_select_all:'All collections', add:'Add', cart_empty:'Your cart is empty.',
    about_eyebrow:'Our root', about_title:'More than products, a way of living.', about_text:'Raíces brings real foods, herbal rituals, simple objects and practical knowledge into an elegant, warm and sustainable wellness experience.',
    naturals_eyebrow:'Naturals · Coming soon', naturals_text:'The Naturals line will remain reserved until Raíces is ready to launch supplements with the confidence, quality and clarity the brand requires.', waitlist_eyebrow:'Join the waitlist', waitlist_title:'Receive launch updates.', waitlist_btn:'Join the list',
    community_eyebrow:'Raíces Community', community_title:'Join the Raíces community.', community_text:'Receive launches, rituals, recipes and exclusive benefits before anyone else.', newsletter_benefit_1:'Early launches', newsletter_benefit_2:'Recipes and rituals', newsletter_benefit_3:'Exclusive benefits', newsletter_name_label:'Name', newsletter_consent:'I agree to receive Raíces communications about launches, products, recipes and updates.', newsletter_sending:'Sending...', newsletter_invalid_email:'Enter a valid email.', newsletter_consent_error:'Please accept receiving Raíces communications.', newsletter_success:'Thank you for joining Raíces. We will send updates soon.', newsletter_error:'We could not save your email. Try again or message us on WhatsApp.', subscribe:'Subscribe',
    cart_title:'Your cart', subtotal:'Subtotal', delivery_label:'Delivery', total_label:'Total', delivery_zip_label:'Delivery ZIP Code', delivery_apply:'Apply', delivery_prompt:'Enter your ZIP Code to calculate delivery.', cart_note:'Taxes and the final total will be confirmed during payment.', checkout_soon:'Notify me when orders open', waitlist_checkout_eyebrow:'Orders coming soon', waitlist_checkout_title:'We are preparing the official launch.', waitlist_checkout_text:'We are not accepting orders yet while we finish packaging and launch details. Leave your email and we will notify you when the store opens.', waitlist_name_label:'Name', waitlist_consent:'I agree to receive Raíces communications about launches, products and updates.', waitlist_submit:'Notify me when orders open', help:'Need help?',
    signupMarketingConsent:'I want to receive news, inspiration and offers from Raíces by email. I can unsubscribe at any time.',
    account_eyebrow:'Raíces Account', account_title:'My account', account_intro:'Create your account or sign in to save your details, prepare your cart and view your orders.', login:'Sign in', signup:'Create account', enter:'Sign in', forgot:'Forgot password', confirm_email_note:'Check your email to confirm registration.', logout:'Sign out', footer_love:'Made with love · For you and for the planet',
    profile:'Profile', orders:'Orders', addresses:'Addresses', coming:'Coming soon', view_product:'View product', benefits:'Benefits', ingredients:'Ingredients', conservation:'Storage', preparation:'Preparation', ideal_moment:'Ideal moment', related:'Complete your ritual', close:'Close', add_to_cart:'Add to cart', sold_out:'Temporarily sold out', notify_product:'Notify me', notify_product_title:'We will let you know when it is back', notify_product_text:'Leave your email and we will notify you when this product is available again.'
  }
};

window.raicesLang = localStorage.getItem('raices_lang') || 'es';
window.raicesT = function(key){ return (window.RAICES_I18N[window.raicesLang] && window.RAICES_I18N[window.raicesLang][key]) || key; };
window.applyRaicesLanguage = function(lang){
  window.raicesLang = lang || window.raicesLang || 'es';
  localStorage.setItem('raices_lang', window.raicesLang);
  document.documentElement.lang = window.raicesLang;
  document.querySelectorAll('[data-i18n]').forEach(function(el){
    const key = el.getAttribute('data-i18n');
    if(window.RAICES_I18N[window.raicesLang] && window.RAICES_I18N[window.raicesLang][key]) el.textContent = window.RAICES_I18N[window.raicesLang][key];
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el){
    const key = el.getAttribute('data-i18n-placeholder');
    if(window.RAICES_I18N[window.raicesLang] && window.RAICES_I18N[window.raicesLang][key]) el.setAttribute('placeholder', window.RAICES_I18N[window.raicesLang][key]);
  });
  const label = window.raicesLang === 'es' ? 'ES ▾' : 'EN ▾';
  const lb = document.getElementById('langBtn'); if(lb) lb.textContent = label;
  const dl = document.getElementById('drawerLangBtn'); if(dl) dl.textContent = label;
  const emailInput = document.getElementById('emailInput'); if(emailInput) emailInput.placeholder = window.raicesLang === 'es' ? 'Tu correo electrónico' : 'Your email address';
  const newsletterName = document.getElementById('newsletterName'); if(newsletterName) newsletterName.placeholder = window.raicesLang === 'es' ? 'Tu nombre' : 'Your name';
  const waitlistName = document.getElementById('waitlistName'); if(waitlistName) waitlistName.placeholder = window.raicesLang === 'es' ? 'Tu nombre' : 'Your name';
  const waitlistEmail = document.getElementById('waitlistEmail'); if(waitlistEmail) waitlistEmail.placeholder = window.raicesLang === 'es' ? 'tu@email.com' : 'you@email.com';
  window.dispatchEvent(new CustomEvent('raices:languageChanged'));
};

document.addEventListener('DOMContentLoaded', function(){
  const toggle = function(){ window.applyRaicesLanguage(window.raicesLang === 'es' ? 'en' : 'es'); };
  const lb = document.getElementById('langBtn'); if(lb) lb.addEventListener('click', toggle);
  const dl = document.getElementById('drawerLangBtn'); if(dl) dl.addEventListener('click', toggle);
  window.applyRaicesLanguage(window.raicesLang);
});
