(function(){
  const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const token=new URLSearchParams(location.search).get('token')||'';
  let lang=localStorage.getItem('raices_lang')==='en'?'en':'es', state=null, requestBusy=false;
  const T={
    es:{title:'Gestionar pedido',order:'Pedido',status:'Estado',total:'Total pagado',date:'Fecha',cancel:'Solicitar cancelación',cancelInfo:'Puedes solicitar la cancelación mientras el pedido no haya salido a entrega. La solicitud será revisada antes de procesar cualquier reembolso.',cancelBlocked:'Tu pedido ya está en camino. En este momento no es posible solicitar su cancelación online. Si necesitas ayuda, contáctanos.',return:'Solicitar devolución Home',issue:'Reportar un problema',returnInfo:'Los productos Home elegibles pueden solicitar devolución dentro de 14 días desde la entrega.',noReturn:'La ventana de devolución Home de 14 días ya finalizó.',selectItems:'Selecciona los productos',reason:'Motivo',note:'Cuéntanos brevemente qué ocurrió',photos:'Fotos / evidencia',send:'Enviar solicitud',close:'Cerrar',pending:'Solicitudes existentes',noRequests:'No hay solicitudes postventa para este pedido.',sent:'Solicitud enviada correctamente. Te enviaremos un email con las próximas actualizaciones.',error:'No pudimos enviar la solicitud. Intenta de nuevo.',foodNote:'Alimentos e infusiones no se devuelven por cambio de opinión después de la entrega. Sí puedes reportar cualquier incidencia.',changeMind:'Cambié de opinión',orderedMistake:'Hice el pedido por error',duplicateOrder:'Pedido duplicado',changeItems:'Necesito cambiar productos o cantidades',deliveryTiming:'El horario de entrega ya no me funciona',otherExplain:'Describe brevemente el motivo para continuar.',damaged:'Dañado',broken:'Roto',incorrect:'Producto incorrecto',missing:'Producto faltante / piezas faltantes',quality:'Problema de calidad',other:'Otro',photoRequired:'Para productos rotos o dañados, adjunta al menos una foto.',homeOnly:'Solo los productos Home pueden incluirse en una devolución normal.',back:'Volver a la tienda'},
    en:{title:'Manage order',order:'Order',status:'Status',total:'Total paid',date:'Date',cancel:'Request cancellation',cancelInfo:'You may request cancellation while the order has not gone out for delivery. The request is reviewed before any refund is processed.',cancelBlocked:'This order is already in the delivery process and can no longer be canceled online.',return:'Request Home return',issue:'Report a problem',returnInfo:'Eligible Home products may be requested for return within 14 days after delivery.',noReturn:'The 14-day Home return window has ended.',selectItems:'Select products',reason:'Reason',note:'Briefly tell us what happened',photos:'Photos / evidence',send:'Submit request',close:'Close',pending:'Existing requests',noRequests:'There are no post-sale requests for this order.',sent:'Your request was submitted. We will email you with updates.',error:'We could not submit the request. Please try again.',foodNote:'Food and herbal infusions are not returnable for change of mind after delivery. You may still report any problem.',changeMind:'Changed my mind',orderedMistake:'I placed the order by mistake',duplicateOrder:'Duplicate order',changeItems:'I need to change products or quantities',deliveryTiming:'The delivery timing no longer works for me',otherExplain:'Briefly describe the reason to continue.',damaged:'Damaged',broken:'Broken',incorrect:'Incorrect product',missing:'Missing product / parts',quality:'Quality issue',other:'Other',photoRequired:'For broken or damaged items, attach at least one photo.',homeOnly:'Only Home products may be included in a standard return.',back:'Back to store'}
  };
  const t=k=>T[lang][k]||k; const money=n=>new Intl.NumberFormat(lang==='en'?'en-US':'es-US',{style:'currency',currency:'USD'}).format(Number(n||0));
  function statusLabel(s){const m={pending:lang==='en'?'Pending review':'Pendiente de revisión',approved:lang==='en'?'Approved':'Aprobada',awaiting_return:lang==='en'?'Waiting for return':'Esperando devolución',received:lang==='en'?'Received':'Recibida',inspection:lang==='en'?'Inspection':'En inspección',refunded:lang==='en'?'Refunded':'Reembolsada',replacement:lang==='en'?'Replacement approved':'Reemplazo aprobado',rejected:lang==='en'?'Rejected':'Rechazada',closed:lang==='en'?'Closed':'Cerrada'};return m[s]||s;}
  function typeLabel(s){return {cancellation:lang==='en'?'Cancellation':'Cancelación',home_return:lang==='en'?'Home return':'Devolución Home',issue:lang==='en'?'Issue':'Incidencia'}[s]||s;}
  function render(){if(!state)return; document.documentElement.lang=lang; $('manageEs').classList.toggle('active',lang==='es');$('manageEn').classList.toggle('active',lang==='en');
    const o=state.order, home=o.order_items.filter(i=>i.is_home), physical=o.order_items.filter(i=>i.operational_type!=='digital');
    $('manageContent').innerHTML=`<section class="manage-card"><h1>${t('title')}</h1><div class="manage-summary"><div><span>${t('order')}</span><strong>#${esc(o.order_number||'')}</strong></div><div><span>${t('status')}</span><strong>${esc(o.status||'')}</strong></div><div><span>${t('total')}</span><strong>${money(o.total_amount)}</strong></div></div></section>
    <section class="manage-card"><h2>${lang==='en'?'Available options':'Opciones disponibles'}</h2>${state.cancellationEligible?`<div class="manage-alert">${t('cancelInfo')}</div><div class="manage-actions"><button class="manage-btn" data-action="cancellation">${t('cancel')}</button></div>`:(state.delivered?'':`<div class="manage-alert">${t('cancelBlocked')}</div>`)}
    ${state.delivered?`${home.length?(state.withinReturnWindow?`<p>${t('returnInfo')}</p><button class="manage-btn secondary" data-action="home_return">${t('return')}</button>`:`<div class="manage-alert">${t('noReturn')}</div>`):''}<p class="manage-muted">${t('foodNote')}</p><button class="manage-btn secondary" data-action="issue">${t('issue')}</button>`:''}</section>
    <section class="manage-card"><h2>${t('pending')}</h2><div class="manage-status-list">${(state.requests||[]).length?state.requests.map(r=>`<article><strong>${typeLabel(r.request_type)}</strong><br><span>${statusLabel(r.status)}</span><br><small>${new Date(r.created_at).toLocaleString(lang==='en'?'en-US':'es-US')}</small></article>`).join(''):`<p>${t('noRequests')}</p>`}</div></section>
    <a class="manage-btn secondary" href="/">${t('back')}</a>`;
    $('manageContent').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>openForm(b.dataset.action));
  }
  function itemChecks(items){return `<div class="manage-items">${items.map(i=>`<label class="manage-item"><input type="checkbox" name="item" value="${esc(i.id)}" checked><span><strong>${esc(i.product_name)}</strong><br><small>${Number(i.quantity||1)} × ${money(i.unit_price||0)}${i.is_home?' · Home':''}</small></span></label>`).join('')}</div>`;}
  function openForm(type){const o=state.order; let items=o.order_items; if(type==='home_return')items=items.filter(i=>i.is_home); const isCancel=type==='cancellation';
    $('manageModalBody').innerHTML=`<h2>${type==='cancellation'?t('cancel'):type==='home_return'?t('return'):t('issue')}</h2><form id="postSaleForm" class="manage-form">${!isCancel?`<label>${t('selectItems')}${itemChecks(items)}</label>`:''}<label>${t('reason')}<select id="postReason">${type==='cancellation'?`<option value="change_mind">${t('changeMind')}</option><option value="ordered_by_mistake">${t('orderedMistake')}</option><option value="duplicate_order">${t('duplicateOrder')}</option><option value="change_items">${t('changeItems')}</option><option value="delivery_timing">${t('deliveryTiming')}</option><option value="other">${t('other')}</option>`:type==='home_return'?`<option value="change_mind">${t('changeMind')}</option><option value="other">${t('other')}</option>`:`<option value="damaged">${t('damaged')}</option><option value="broken">${t('broken')}</option><option value="incorrect">${t('incorrect')}</option><option value="missing">${t('missing')}</option><option value="quality">${t('quality')}</option><option value="other">${t('other')}</option>`}</select></label><label>${t('note')}<textarea id="postNote" maxlength="1800"></textarea></label>${type==='issue'?`<label>${t('photos')}<input id="postImages" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><p class="manage-muted">${t('photoRequired')}</p>`:''}<div id="postMessage"></div><div class="manage-actions"><button type="submit" class="manage-btn">${t('send')}</button><button type="button" class="manage-btn secondary" id="postCancel">${t('close')}</button></div></form>`;
    $('manageModal').hidden=false;$('postCancel').onclick=closeModal;$('postSaleForm').onsubmit=e=>submitForm(e,type);
  }
  function closeModal(){$('manageModal').hidden=true;}
  async function filesToData(files){const out=[];for(const f of [...files].slice(0,4)){if(f.size>8*1024*1024)throw new Error('FILE_TOO_LARGE');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)});out.push({mime:f.type||'image/jpeg',data});}return out;}
  async function submitForm(e,type){e.preventDefault();if(requestBusy)return;const msg=$('postMessage');msg.className='';msg.textContent=''; const ids=type==='cancellation'?[]:[...document.querySelectorAll('input[name=item]:checked')].map(x=>x.value);if(type!=='cancellation'&&!ids.length){msg.className='manage-alert error';msg.textContent=t('selectItems');return;}requestBusy=true;try{const files=$('postImages')?.files||[];const images=await filesToData(files);const reason=$('postReason')?.value||(type==='cancellation'?'change_mind':'');const customerNote=$('postNote')?.value?.trim()||'';if(type==='cancellation'&&reason==='other'&&!customerNote){msg.className='manage-alert error';msg.textContent=t('otherExplain');requestBusy=false;return;}if(type==='issue'&&['damaged','broken'].includes(reason)&&!images.length){throw new Error('PHOTO_REQUIRED')}const res=await fetch('/.netlify/functions/post-sale-request',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,request_type:type,order_item_ids:ids,reason,customer_note:customerNote,images})});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'REQUEST_ERROR');msg.className='manage-alert success';msg.textContent=t('sent');await load();setTimeout(closeModal,1500);}catch(err){
    msg.className='manage-alert error';
    if(err.message==='PHOTO_REQUIRED') msg.textContent=t('photoRequired');
    else if(type==='cancellation'&&err.message==='CANCELLATION_NOT_AVAILABLE'){
      msg.textContent=t('cancelBlocked');
      await load();
    } else msg.textContent=t('error');
  }finally{requestBusy=false}}
  async function load(){$('manageLoading').hidden=false;$('manageContent').hidden=true;try{const res=await fetch(`/.netlify/functions/post-sale-request?token=${encodeURIComponent(token)}`,{cache:'no-store'});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'NOT_FOUND');state=body;$('manageLoading').hidden=true;$('manageContent').hidden=false;render();}catch(err){$('manageLoading').innerHTML=`<h1>${t('title')}</h1><div class="manage-alert error">${lang==='en'?'We could not open this order. Check the secure link or contact Raíces.':'No pudimos abrir este pedido. Revisa el enlace seguro o contacta a Raíces.'}</div>`;}}
  $('manageClose').onclick=closeModal;$('manageModal').onclick=e=>{if(e.target===$('manageModal'))closeModal()};$('manageEs').onclick=()=>{lang='es';localStorage.setItem('raices_lang',lang);render()};$('manageEn').onclick=()=>{lang='en';localStorage.setItem('raices_lang',lang);render()};load();
})();
