window.RAICES_PRODUCTS = [
  {
    "sku": "RA-AR-001",
    "category": "Kitchen",
    "collection": "Signature Arepas",
    "subcategory": "Arepas",
    "name": "Yuca Clásica",
    "slug": "yuca-clasica",
    "description": "Arepa artesanal de yuca clásica elaborada para calentar, servir y disfrutar en casa.",
    "longDescription": "Yuca Clásica forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.",
    "unit": "Paquete",
    "unitsPerPackage": 6,
    "unitWeight": "113 g (4 oz)",
    "netWeight": "680 g (24 oz)",
    "price": 18.0,
    "image": "assets/products/arepas/arepa-yuca-clasica.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Hechas con raíces e ingredientes reales",
      "Sin conservantes artificiales",
      "Listas para calentar y compartir"
    ],
    "ingredients": "Yuca y mezcla natural según variedad.",
    "conservation": "Mantener congelado. Cerrar bien el empaque después de abrir.",
    "preparation": "Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.",
    "moment": "Desayuno, cena ligera o acompañamiento saludable.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-AR-002",
    "category": "Kitchen",
    "collection": "Signature Arepas",
    "subcategory": "Arepas",
    "name": "Yuca + Zanahoria",
    "slug": "yuca-zanahoria",
    "description": "Arepa artesanal de yuca + zanahoria elaborada para calentar, servir y disfrutar en casa.",
    "longDescription": "Yuca + Zanahoria forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.",
    "unit": "Paquete",
    "unitsPerPackage": 6,
    "unitWeight": "113 g (4 oz)",
    "netWeight": "680 g (24 oz)",
    "price": 19.0,
    "image": "assets/products/arepas/arepa-yuca-zanahoria.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Hechas con raíces e ingredientes reales",
      "Sin conservantes artificiales",
      "Listas para calentar y compartir"
    ],
    "ingredients": "Yuca y mezcla natural según variedad.",
    "conservation": "Mantener congelado. Cerrar bien el empaque después de abrir.",
    "preparation": "Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.",
    "moment": "Desayuno, cena ligera o acompañamiento saludable.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-AR-003",
    "category": "Kitchen",
    "collection": "Signature Arepas",
    "subcategory": "Arepas",
    "name": "Yuca + Remolacha",
    "slug": "yuca-remolacha",
    "description": "Arepa artesanal de yuca + remolacha elaborada para calentar, servir y disfrutar en casa.",
    "longDescription": "Yuca + Remolacha forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.",
    "unit": "Paquete",
    "unitsPerPackage": 6,
    "unitWeight": "113 g (4 oz)",
    "netWeight": "680 g (24 oz)",
    "price": 19.0,
    "image": "assets/products/arepas/arepa-yuca-remolacha.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Hechas con raíces e ingredientes reales",
      "Sin conservantes artificiales",
      "Listas para calentar y compartir"
    ],
    "ingredients": "Yuca y mezcla natural según variedad.",
    "conservation": "Mantener congelado. Cerrar bien el empaque después de abrir.",
    "preparation": "Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.",
    "moment": "Desayuno, cena ligera o acompañamiento saludable.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-AR-004",
    "category": "Kitchen",
    "collection": "Signature Arepas",
    "subcategory": "Arepas",
    "name": "Yuca + Cúrcuma",
    "slug": "yuca-curcuma",
    "description": "Arepa artesanal de yuca + cúrcuma elaborada para calentar, servir y disfrutar en casa.",
    "longDescription": "Yuca + Cúrcuma forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.",
    "unit": "Paquete",
    "unitsPerPackage": 6,
    "unitWeight": "113 g (4 oz)",
    "netWeight": "680 g (24 oz)",
    "price": 19.0,
    "image": "assets/products/arepas/arepa-yuca-curcuma.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Hechas con raíces e ingredientes reales",
      "Sin conservantes artificiales",
      "Listas para calentar y compartir"
    ],
    "ingredients": "Yuca y mezcla natural según variedad.",
    "conservation": "Mantener congelado. Cerrar bien el empaque después de abrir.",
    "preparation": "Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.",
    "moment": "Desayuno, cena ligera o acompañamiento saludable.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-AR-005",
    "category": "Kitchen",
    "collection": "Signature Arepas",
    "subcategory": "Arepas",
    "name": "Yuca + Ajo Asado & Romero",
    "slug": "yuca-ajo-asado-and-romero",
    "description": "Arepa artesanal de yuca + ajo asado & romero elaborada para calentar, servir y disfrutar en casa.",
    "longDescription": "Yuca + Ajo Asado & Romero forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.",
    "unit": "Paquete",
    "unitsPerPackage": 6,
    "unitWeight": "113 g (4 oz)",
    "netWeight": "680 g (24 oz)",
    "price": 19.0,
    "image": "assets/products/arepas/arepa-yuca-ajo-romero.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Hechas con raíces e ingredientes reales",
      "Sin conservantes artificiales",
      "Listas para calentar y compartir"
    ],
    "ingredients": "Yuca y mezcla natural según variedad.",
    "conservation": "Mantener congelado. Cerrar bien el empaque después de abrir.",
    "preparation": "Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.",
    "moment": "Desayuno, cena ligera o acompañamiento saludable.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-AR-006",
    "category": "Kitchen",
    "collection": "Signature Arepas",
    "subcategory": "Arepas",
    "name": "Yuca 4 Seeds",
    "slug": "yuca-4-seeds",
    "description": "Arepa artesanal de yuca 4 seeds elaborada para calentar, servir y disfrutar en casa.",
    "longDescription": "Yuca 4 Seeds forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.",
    "unit": "Paquete",
    "unitsPerPackage": 6,
    "unitWeight": "113 g (4 oz)",
    "netWeight": "680 g (24 oz)",
    "price": 20.0,
    "image": "assets/products/arepas/arepa-yuca-4-seeds.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Hechas con raíces e ingredientes reales",
      "Sin conservantes artificiales",
      "Listas para calentar y compartir"
    ],
    "ingredients": "Yuca y mezcla natural según variedad.",
    "conservation": "Mantener congelado. Cerrar bien el empaque después de abrir.",
    "preparation": "Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.",
    "moment": "Desayuno, cena ligera o acompañamiento saludable.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-AR-007",
    "category": "Kitchen",
    "collection": "Signature Arepas",
    "subcategory": "Arepas",
    "name": "Batata & Yuca",
    "slug": "batata-and-yuca",
    "description": "Arepa artesanal de batata & yuca elaborada para calentar, servir y disfrutar en casa.",
    "longDescription": "Batata & Yuca forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.",
    "unit": "Paquete",
    "unitsPerPackage": 6,
    "unitWeight": "113 g (4 oz)",
    "netWeight": "680 g (24 oz)",
    "price": 20.0,
    "image": "assets/products/arepas/arepa-batata-yuca.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Hechas con raíces e ingredientes reales",
      "Sin conservantes artificiales",
      "Listas para calentar y compartir"
    ],
    "ingredients": "Yuca y mezcla natural según variedad.",
    "conservation": "Mantener congelado. Cerrar bien el empaque después de abrir.",
    "preparation": "Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.",
    "moment": "Desayuno, cena ligera o acompañamiento saludable.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-AR-008",
    "category": "Kitchen",
    "collection": "Signature Arepas",
    "subcategory": "Arepas",
    "name": "Plátano Maduro",
    "slug": "platano-maduro",
    "description": "Arepa artesanal de plátano maduro elaborada para calentar, servir y disfrutar en casa.",
    "longDescription": "Plátano Maduro forma parte de la Signature Arepas Collection de Raíces: arepas de raíz con ingredientes reales, textura suave y una preparación práctica para desayunos, cenas ligeras o acompañamientos.",
    "unit": "Paquete",
    "unitsPerPackage": 6,
    "unitWeight": "113 g (4 oz)",
    "netWeight": "680 g (24 oz)",
    "price": 19.0,
    "image": "assets/products/arepas/arepa-platano-maduro.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Hechas con raíces e ingredientes reales",
      "Sin conservantes artificiales",
      "Listas para calentar y compartir"
    ],
    "ingredients": "Yuca y mezcla natural según variedad.",
    "conservation": "Mantener congelado. Cerrar bien el empaque después de abrir.",
    "preparation": "Calentar en air fryer, sartén u horno hasta dorar. No requiere descongelar por completo.",
    "moment": "Desayuno, cena ligera o acompañamiento saludable.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-EM-001",
    "category": "Kitchen",
    "collection": "Signature Empanadas",
    "subcategory": "Empanadas",
    "name": "Yuca Clásica + Pollo Mechado",
    "slug": "yuca-clasica-pollo-mechado",
    "description": "Empanada artesanal yuca clásica + pollo mechado con masa inspirada en raíces naturales y relleno sabroso.",
    "longDescription": "Yuca Clásica + Pollo Mechado combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.",
    "unit": "Paquete",
    "unitsPerPackage": 4,
    "unitWeight": "142 g (5 oz)",
    "netWeight": "568 g (20 oz)",
    "price": 23.0,
    "image": "assets/products/empanadas/empanada-yuca-pollo.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Masa artesanal",
      "Rellenos con sabor casero",
      "Prácticas para air fryer u horno"
    ],
    "ingredients": "Masa de raíz y relleno según variedad.",
    "conservation": "Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.",
    "preparation": "Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.",
    "moment": "Almuerzo rápido, cena práctica o snack salado.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-EM-002",
    "category": "Kitchen",
    "collection": "Signature Empanadas",
    "subcategory": "Empanadas",
    "name": "Yuca + Pavo al Romero",
    "slug": "yuca-pavo-al-romero",
    "description": "Empanada artesanal yuca + pavo al romero con masa inspirada en raíces naturales y relleno sabroso.",
    "longDescription": "Yuca + Pavo al Romero combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.",
    "unit": "Paquete",
    "unitsPerPackage": 4,
    "unitWeight": "142 g (5 oz)",
    "netWeight": "568 g (20 oz)",
    "price": 23.0,
    "image": "assets/emp-yuca-pavo.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Masa artesanal",
      "Rellenos con sabor casero",
      "Prácticas para air fryer u horno"
    ],
    "ingredients": "Masa de raíz y relleno según variedad.",
    "conservation": "Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.",
    "preparation": "Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.",
    "moment": "Almuerzo rápido, cena práctica o snack salado.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-EM-003",
    "category": "Kitchen",
    "collection": "Signature Empanadas",
    "subcategory": "Empanadas",
    "name": "Plátano Maduro + Pollo",
    "slug": "platano-maduro-pollo",
    "description": "Empanada artesanal plátano maduro + pollo con masa inspirada en raíces naturales y relleno sabroso.",
    "longDescription": "Plátano Maduro + Pollo combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.",
    "unit": "Paquete",
    "unitsPerPackage": 4,
    "unitWeight": "142 g (5 oz)",
    "netWeight": "568 g (20 oz)",
    "price": 23.0,
    "image": "assets/products/empanadas/empanada-platano-pollo.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Masa artesanal",
      "Rellenos con sabor casero",
      "Prácticas para air fryer u horno"
    ],
    "ingredients": "Masa de raíz y relleno según variedad.",
    "conservation": "Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.",
    "preparation": "Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.",
    "moment": "Almuerzo rápido, cena práctica o snack salado.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-EM-004",
    "category": "Kitchen",
    "collection": "Signature Empanadas",
    "subcategory": "Empanadas",
    "name": "Yuca + Remolacha + Carne Mechada",
    "slug": "yuca-remolacha-carne-mechada",
    "description": "Empanada artesanal yuca + remolacha + carne mechada con masa inspirada en raíces naturales y relleno sabroso.",
    "longDescription": "Yuca + Remolacha + Carne Mechada combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.",
    "unit": "Paquete",
    "unitsPerPackage": 4,
    "unitWeight": "142 g (5 oz)",
    "netWeight": "568 g (20 oz)",
    "price": 23.0,
    "image": "assets/products/empanadas/empanada-yuca-remolacha-carne.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Masa artesanal",
      "Rellenos con sabor casero",
      "Prácticas para air fryer u horno"
    ],
    "ingredients": "Masa de raíz y relleno según variedad.",
    "conservation": "Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.",
    "preparation": "Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.",
    "moment": "Almuerzo rápido, cena práctica o snack salado.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-EM-005",
    "category": "Kitchen",
    "collection": "Signature Empanadas",
    "subcategory": "Empanadas",
    "name": "Yuca + Cúrcuma + Pollo Curry",
    "slug": "yuca-curcuma-pollo-curry",
    "description": "Empanada artesanal yuca + cúrcuma + pollo curry con masa inspirada en raíces naturales y relleno sabroso.",
    "longDescription": "Yuca + Cúrcuma + Pollo Curry combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.",
    "unit": "Paquete",
    "unitsPerPackage": 4,
    "unitWeight": "142 g (5 oz)",
    "netWeight": "568 g (20 oz)",
    "price": 23.0,
    "image": "assets/products/empanadas/empanada-yuca-curcuma-pollo.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Masa artesanal",
      "Rellenos con sabor casero",
      "Prácticas para air fryer u horno"
    ],
    "ingredients": "Masa de raíz y relleno según variedad.",
    "conservation": "Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.",
    "preparation": "Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.",
    "moment": "Almuerzo rápido, cena práctica o snack salado.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-EM-006",
    "category": "Kitchen",
    "collection": "Signature Empanadas",
    "subcategory": "Empanadas",
    "name": "Yuca + Espinaca + Queso",
    "slug": "yuca-espinaca-queso",
    "description": "Empanada artesanal yuca + espinaca + queso con masa inspirada en raíces naturales y relleno sabroso.",
    "longDescription": "Yuca + Espinaca + Queso combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.",
    "unit": "Paquete",
    "unitsPerPackage": 4,
    "unitWeight": "142 g (5 oz)",
    "netWeight": "568 g (20 oz)",
    "price": 23.0,
    "image": "assets/products/empanadas/empanada-yuca-espinaca-queso.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Masa artesanal",
      "Rellenos con sabor casero",
      "Prácticas para air fryer u horno"
    ],
    "ingredients": "Masa de raíz y relleno según variedad.",
    "conservation": "Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.",
    "preparation": "Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.",
    "moment": "Almuerzo rápido, cena práctica o snack salado.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-EM-007",
    "category": "Kitchen",
    "collection": "Signature Empanadas",
    "subcategory": "Empanadas",
    "name": "Yuca 4 Seeds + Pavo",
    "slug": "yuca-4-seeds-pavo",
    "description": "Empanada artesanal yuca 4 seeds + pavo con masa inspirada en raíces naturales y relleno sabroso.",
    "longDescription": "Yuca 4 Seeds + Pavo combina masa artesanal, color natural y un relleno pensado para una comida práctica con identidad propia. Una empanada creada para sentirse casera, diferente y elevada.",
    "unit": "Paquete",
    "unitsPerPackage": 4,
    "unitWeight": "142 g (5 oz)",
    "netWeight": "568 g (20 oz)",
    "price": 23.0,
    "image": "assets/products/empanadas/empanada-yuca-4-seeds-pavo.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Masa artesanal",
      "Rellenos con sabor casero",
      "Prácticas para air fryer u horno"
    ],
    "ingredients": "Masa de raíz y relleno según variedad.",
    "conservation": "Mantener congelado. Evitar descongelar por tiempo prolongado antes de preparar.",
    "preparation": "Calentar en air fryer u horno hasta lograr exterior dorado y centro caliente.",
    "moment": "Almuerzo rápido, cena práctica o snack salado.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-PC-001",
    "category": "Kitchen",
    "collection": "Protein Craft Collection",
    "subcategory": "Proteínas",
    "name": "Pollo al Romero & Limón",
    "slug": "pollo-al-romero-and-limon",
    "description": "Proteína artesanal pollo al romero & limón, cocinada lentamente y lista para disfrutar.",
    "longDescription": "Pollo al Romero & Limón pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.",
    "unit": "Lbs",
    "unitsPerPackage": 1,
    "unitWeight": "454 g (16 oz)",
    "netWeight": "454 g (16 oz)",
    "price": 16.0,
    "image": "assets/products/proteinas/proteina-pollo-romero-limon.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Alta en proteína",
      "Cocinada lentamente",
      "Lista para combinar con arepas, bowls o ensaladas"
    ],
    "ingredients": "Proteína principal, hierbas y condimentos naturales según variedad.",
    "conservation": "Mantener refrigerado o congelado según fecha de producción. Consumir después de calentar completamente.",
    "preparation": "Calentar en sartén, microondas u horno hasta alcanzar temperatura adecuada.",
    "moment": "Meal prep, bowls, cenas rápidas o complemento de platos principales.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-PC-002",
    "category": "Kitchen",
    "collection": "Protein Craft Collection",
    "subcategory": "Proteínas",
    "name": "Carne Mechada Signature",
    "slug": "carne-mechada-signature",
    "description": "Proteína artesanal carne mechada signature, cocinada lentamente y lista para disfrutar.",
    "longDescription": "Carne Mechada Signature pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.",
    "unit": "Lbs",
    "unitsPerPackage": 1,
    "unitWeight": "454 g (16 oz)",
    "netWeight": "454 g (16 oz)",
    "price": 19.0,
    "image": "assets/products/proteinas/proteina-carne-mechada.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Alta en proteína",
      "Cocinada lentamente",
      "Lista para combinar con arepas, bowls o ensaladas"
    ],
    "ingredients": "Proteína principal, hierbas y condimentos naturales según variedad.",
    "conservation": "Mantener refrigerado o congelado según fecha de producción. Consumir después de calentar completamente.",
    "preparation": "Calentar en sartén, microondas u horno hasta alcanzar temperatura adecuada.",
    "moment": "Meal prep, bowls, cenas rápidas o complemento de platos principales.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-PC-003",
    "category": "Kitchen",
    "collection": "Protein Craft Collection",
    "subcategory": "Proteínas",
    "name": "Pavo Molido Mediterráneo",
    "slug": "pavo-molido-mediterraneo",
    "description": "Proteína artesanal pavo molido mediterráneo, cocinada lentamente y lista para disfrutar.",
    "longDescription": "Pavo Molido Mediterráneo pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.",
    "unit": "Lbs",
    "unitsPerPackage": 1,
    "unitWeight": "454 g (16 oz)",
    "netWeight": "454 g (16 oz)",
    "price": 17.0,
    "image": "assets/products/proteinas/proteina-pavo-mediterraneo.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Alta en proteína",
      "Cocinada lentamente",
      "Lista para combinar con arepas, bowls o ensaladas"
    ],
    "ingredients": "Proteína principal, hierbas y condimentos naturales según variedad.",
    "conservation": "Mantener refrigerado o congelado según fecha de producción. Consumir después de calentar completamente.",
    "preparation": "Calentar en sartén, microondas u horno hasta alcanzar temperatura adecuada.",
    "moment": "Meal prep, bowls, cenas rápidas o complemento de platos principales.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-PC-004",
    "category": "Kitchen",
    "collection": "Protein Craft Collection",
    "subcategory": "Proteínas",
    "name": "Pescado al Limón & Hierbas",
    "slug": "pescado-al-limon-and-hierbas",
    "description": "Proteína artesanal pescado al limón & hierbas, cocinada lentamente y lista para disfrutar.",
    "longDescription": "Pescado al Limón & Hierbas pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.",
    "unit": "Lbs",
    "unitsPerPackage": 1,
    "unitWeight": "454 g (16 oz)",
    "netWeight": "454 g (16 oz)",
    "price": 20.0,
    "image": "assets/products/proteinas/proteina-pescado-limon-hierbas.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Alta en proteína",
      "Cocinada lentamente",
      "Lista para combinar con arepas, bowls o ensaladas"
    ],
    "ingredients": "Proteína principal, hierbas y condimentos naturales según variedad.",
    "conservation": "Mantener refrigerado o congelado según fecha de producción. Consumir después de calentar completamente.",
    "preparation": "Calentar en sartén, microondas u horno hasta alcanzar temperatura adecuada.",
    "moment": "Meal prep, bowls, cenas rápidas o complemento de platos principales.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-PC-005",
    "category": "Kitchen",
    "collection": "Protein Craft Collection",
    "subcategory": "Proteínas",
    "name": "Cerdo al Ajo Asado & Tomillo",
    "slug": "cerdo-al-ajo-asado-and-tomillo",
    "description": "Proteína artesanal cerdo al ajo asado & tomillo, cocinada lentamente y lista para disfrutar.",
    "longDescription": "Cerdo al Ajo Asado & Tomillo pertenece a la Protein Craft Collection: proteínas preparadas con intención, listas para facilitar comidas balanceadas sin sacrificar sabor ni calidad.",
    "unit": "Lbs",
    "unitsPerPackage": 1,
    "unitWeight": "454 g (16 oz)",
    "netWeight": "454 g (16 oz)",
    "price": 17.0,
    "image": "assets/products/proteinas/proteina-cerdo-ajo-tomillo.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Alta en proteína",
      "Cocinada lentamente",
      "Lista para combinar con arepas, bowls o ensaladas"
    ],
    "ingredients": "Proteína principal, hierbas y condimentos naturales según variedad.",
    "conservation": "Mantener refrigerado o congelado según fecha de producción. Consumir después de calentar completamente.",
    "preparation": "Calentar en sartén, microondas u horno hasta alcanzar temperatura adecuada.",
    "moment": "Meal prep, bowls, cenas rápidas o complemento de platos principales.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-TM-001",
    "category": "Herbal",
    "collection": "Three Moments",
    "subcategory": "Herbal",
    "name": "Slim & Drain",
    "slug": "slim-and-drain",
    "description": "Mezcla herbal Slim & Drain creada para acompañar un momento específico de tu día.",
    "longDescription": "Slim & Drain forma parte del universo Herbal de Raíces: infusiones pensadas como pequeños rituales diarios para reconectar con el cuerpo, la pausa y la intención.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "60 g (2.11 oz)",
    "netWeight": "60 g (2.11 oz)",
    "price": 19.0,
    "image": "assets/products/herbal/te-slim-drain.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Mezcla herbal natural",
      "Ritual diario de bienestar",
      "Empaque pensado para regalar o disfrutar"
    ],
    "ingredients": "Mezcla de hierbas e ingredientes botánicos.",
    "conservation": "Conservar en lugar fresco y seco. Mantener cerrado después de abrir.",
    "preparation": "Infusionar en agua caliente de 5 a 8 minutos. Ajustar intensidad al gusto.",
    "moment": "Mañana, tarde o noche según el ritual elegido.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-TM-002",
    "category": "Herbal",
    "collection": "Three Moments",
    "subcategory": "Herbal",
    "name": "Golden Fit",
    "slug": "golden-fit",
    "description": "Mezcla herbal Golden Fit creada para acompañar un momento específico de tu día.",
    "longDescription": "Golden Fit forma parte del universo Herbal de Raíces: infusiones pensadas como pequeños rituales diarios para reconectar con el cuerpo, la pausa y la intención.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "60 g (2.11 oz)",
    "netWeight": "60 g (2.11 oz)",
    "price": 20.0,
    "image": "assets/products/herbal/te-golden-fit.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Mezcla herbal natural",
      "Ritual diario de bienestar",
      "Empaque pensado para regalar o disfrutar"
    ],
    "ingredients": "Mezcla de hierbas e ingredientes botánicos.",
    "conservation": "Conservar en lugar fresco y seco. Mantener cerrado después de abrir.",
    "preparation": "Infusionar en agua caliente de 5 a 8 minutos. Ajustar intensidad al gusto.",
    "moment": "Mañana, tarde o noche según el ritual elegido.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-TM-003",
    "category": "Herbal",
    "collection": "Three Moments",
    "subcategory": "Herbal",
    "name": "Dream & Calm",
    "slug": "dream-and-calm",
    "description": "Mezcla herbal Dream & Calm creada para acompañar un momento específico de tu día.",
    "longDescription": "Dream & Calm forma parte del universo Herbal de Raíces: infusiones pensadas como pequeños rituales diarios para reconectar con el cuerpo, la pausa y la intención.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "60 g (2.11 oz)",
    "netWeight": "60 g (2.11 oz)",
    "price": 19.0,
    "image": "assets/products/herbal/te-dream-calm.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Mezcla herbal natural",
      "Ritual diario de bienestar",
      "Empaque pensado para regalar o disfrutar"
    ],
    "ingredients": "Mezcla de hierbas e ingredientes botánicos.",
    "conservation": "Conservar en lugar fresco y seco. Mantener cerrado después de abrir.",
    "preparation": "Infusionar en agua caliente de 5 a 8 minutos. Ajustar intensidad al gusto.",
    "moment": "Mañana, tarde o noche según el ritual elegido.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-RC-001",
    "category": "Herbal",
    "collection": "Ritual Collection",
    "subcategory": "Herbal",
    "name": "Ritual Collection",
    "slug": "ritual-collection",
    "description": "Mezcla herbal Ritual Collection creada para acompañar un momento específico de tu día.",
    "longDescription": "Ritual Collection forma parte del universo Herbal de Raíces: infusiones pensadas como pequeños rituales diarios para reconectar con el cuerpo, la pausa y la intención.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "60 g (2.11 oz)",
    "netWeight": "60 g (2.11 oz)",
    "price": 30.0,
    "image": "assets/herbal-board.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Mezcla herbal natural",
      "Ritual diario de bienestar",
      "Empaque pensado para regalar o disfrutar"
    ],
    "ingredients": "Mezcla de hierbas e ingredientes botánicos.",
    "conservation": "Conservar en lugar fresco y seco. Mantener cerrado después de abrir.",
    "preparation": "Infusionar en agua caliente de 5 a 8 minutos. Ajustar intensidad al gusto.",
    "moment": "Mañana, tarde o noche según el ritual elegido.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-RB-001",
    "category": "Herbal",
    "collection": "Ritual Box",
    "subcategory": "Herbal",
    "name": "Ritual Box",
    "slug": "ritual-box",
    "description": "Mezcla herbal Ritual Box creada para acompañar un momento específico de tu día.",
    "longDescription": "Ritual Box forma parte del universo Herbal de Raíces: infusiones pensadas como pequeños rituales diarios para reconectar con el cuerpo, la pausa y la intención.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "60 g (2.11 oz)",
    "netWeight": "60 g (2.11 oz)",
    "price": 50.0,
    "image": "assets/herbal-board.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Mezcla herbal natural",
      "Ritual diario de bienestar",
      "Empaque pensado para regalar o disfrutar"
    ],
    "ingredients": "Mezcla de hierbas e ingredientes botánicos.",
    "conservation": "Conservar en lugar fresco y seco. Mantener cerrado después de abrir.",
    "preparation": "Infusionar en agua caliente de 5 a 8 minutos. Ajustar intensidad al gusto.",
    "moment": "Mañana, tarde o noche según el ritual elegido.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-DE-001",
    "category": "Desserts",
    "collection": "Signature Desserts",
    "subcategory": "Postres",
    "name": "Sweet Potato Cake",
    "slug": "sweet-potato-cake",
    "description": "Postre artesanal Sweet Potato Cake, hecho para disfrutar despacio y con ingredientes reales.",
    "longDescription": "Sweet Potato Cake representa la línea Signature Desserts de Raíces: postres con personalidad, porciones generosas y una visión más consciente de lo dulce.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "340 g (12 oz)",
    "netWeight": "340 g (12 oz)",
    "price": 12.0,
    "image": "assets/products/desserts/cake-sweet-potato.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Hecho con ingredientes reales",
      "Porción lista para disfrutar",
      "Lo dulce también puede nutrir"
    ],
    "ingredients": "Ingredientes naturales según variedad.",
    "conservation": "Mantener refrigerado. Consumir dentro del periodo indicado en la etiqueta.",
    "preparation": "Servir frío o dejar reposar unos minutos antes de disfrutar.",
    "moment": "Merienda, postre o detalle especial para compartir.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-DE-002",
    "category": "Desserts",
    "collection": "Signature Desserts",
    "subcategory": "Postres",
    "name": "Beet Velvet Cake",
    "slug": "beet-velvet-cake",
    "description": "Postre artesanal Beet Velvet Cake, hecho para disfrutar despacio y con ingredientes reales.",
    "longDescription": "Beet Velvet Cake representa la línea Signature Desserts de Raíces: postres con personalidad, porciones generosas y una visión más consciente de lo dulce.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "340 g (12 oz)",
    "netWeight": "340 g (12 oz)",
    "price": 13.0,
    "image": "assets/products/desserts/cake-beet-velvet.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Hecho con ingredientes reales",
      "Porción lista para disfrutar",
      "Lo dulce también puede nutrir"
    ],
    "ingredients": "Ingredientes naturales según variedad.",
    "conservation": "Mantener refrigerado. Consumir dentro del periodo indicado en la etiqueta.",
    "preparation": "Servir frío o dejar reposar unos minutos antes de disfrutar.",
    "moment": "Merienda, postre o detalle especial para compartir.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-DE-003",
    "category": "Desserts",
    "collection": "Signature Desserts",
    "subcategory": "Postres",
    "name": "Carrot Cake",
    "slug": "carrot-cake",
    "description": "Postre artesanal Carrot Cake, hecho para disfrutar despacio y con ingredientes reales.",
    "longDescription": "Carrot Cake representa la línea Signature Desserts de Raíces: postres con personalidad, porciones generosas y una visión más consciente de lo dulce.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "340 g (12 oz)",
    "netWeight": "340 g (12 oz)",
    "price": 12.0,
    "image": "assets/products/desserts/cake-carrot.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Hecho con ingredientes reales",
      "Porción lista para disfrutar",
      "Lo dulce también puede nutrir"
    ],
    "ingredients": "Ingredientes naturales según variedad.",
    "conservation": "Mantener refrigerado. Consumir dentro del periodo indicado en la etiqueta.",
    "preparation": "Servir frío o dejar reposar unos minutos antes de disfrutar.",
    "moment": "Merienda, postre o detalle especial para compartir.",
    "relatedHint": "Combina con otros productos Raíces"
  },
  {
    "sku": "RA-HM-001",
    "category": "Home",
    "collection": "Home Rituals",
    "subcategory": "Home",
    "name": "Signature Teapot",
    "slug": "signature-teapot",
    "description": "Signature Teapot para convertir una pausa cotidiana en un ritual con intención.",
    "longDescription": "Signature Teapot pertenece a Home Rituals: objetos sencillos, elegantes y funcionales para preparar, servir y disfrutar tus infusiones y momentos de calma.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "",
    "netWeight": "",
    "price": 35.0,
    "image": "assets/home-board.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Diseño consciente",
      "Acompaña rituales diarios",
      "Ideal para combinar con Herbal"
    ],
    "ingredients": "Materiales según producto.",
    "conservation": "Lavar y cuidar según material. Evitar golpes o cambios bruscos de temperatura si aplica.",
    "preparation": "Usar como parte de tu ritual de té, infusión o pausa diaria.",
    "moment": "Ritual de té, regalo o pausa consciente en casa.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-HM-002",
    "category": "Home",
    "collection": "Home Rituals",
    "subcategory": "Home",
    "name": "Travel Infuser",
    "slug": "travel-infuser",
    "description": "Travel Infuser para convertir una pausa cotidiana en un ritual con intención.",
    "longDescription": "Travel Infuser pertenece a Home Rituals: objetos sencillos, elegantes y funcionales para preparar, servir y disfrutar tus infusiones y momentos de calma.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "",
    "netWeight": "",
    "price": 23.0,
    "image": "assets/home-board.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Diseño consciente",
      "Acompaña rituales diarios",
      "Ideal para combinar con Herbal"
    ],
    "ingredients": "Materiales según producto.",
    "conservation": "Lavar y cuidar según material. Evitar golpes o cambios bruscos de temperatura si aplica.",
    "preparation": "Usar como parte de tu ritual de té, infusión o pausa diaria.",
    "moment": "Ritual de té, regalo o pausa consciente en casa.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-HM-003",
    "category": "Home",
    "collection": "Home Rituals",
    "subcategory": "Home",
    "name": "Infusor Individual",
    "slug": "infusor-individual",
    "description": "Infusor Individual para convertir una pausa cotidiana en un ritual con intención.",
    "longDescription": "Infusor Individual pertenece a Home Rituals: objetos sencillos, elegantes y funcionales para preparar, servir y disfrutar tus infusiones y momentos de calma.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "",
    "netWeight": "",
    "price": 15.0,
    "image": "assets/home-board.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Diseño consciente",
      "Acompaña rituales diarios",
      "Ideal para combinar con Herbal"
    ],
    "ingredients": "Materiales según producto.",
    "conservation": "Lavar y cuidar según material. Evitar golpes o cambios bruscos de temperatura si aplica.",
    "preparation": "Usar como parte de tu ritual de té, infusión o pausa diaria.",
    "moment": "Ritual de té, regalo o pausa consciente en casa.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-HM-004",
    "category": "Home",
    "collection": "Home Rituals",
    "subcategory": "Home",
    "name": "Mug Cerámico",
    "slug": "mug-ceramico",
    "description": "Mug Cerámico para convertir una pausa cotidiana en un ritual con intención.",
    "longDescription": "Mug Cerámico pertenece a Home Rituals: objetos sencillos, elegantes y funcionales para preparar, servir y disfrutar tus infusiones y momentos de calma.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "",
    "netWeight": "",
    "price": 19.0,
    "image": "assets/home-board.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Diseño consciente",
      "Acompaña rituales diarios",
      "Ideal para combinar con Herbal"
    ],
    "ingredients": "Materiales según producto.",
    "conservation": "Lavar y cuidar según material. Evitar golpes o cambios bruscos de temperatura si aplica.",
    "preparation": "Usar como parte de tu ritual de té, infusión o pausa diaria.",
    "moment": "Ritual de té, regalo o pausa consciente en casa.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-HM-005",
    "category": "Home",
    "collection": "Home Rituals",
    "subcategory": "Home",
    "name": "Taza de Vidrio",
    "slug": "taza-de-vidrio",
    "description": "Taza de Vidrio para convertir una pausa cotidiana en un ritual con intención.",
    "longDescription": "Taza de Vidrio pertenece a Home Rituals: objetos sencillos, elegantes y funcionales para preparar, servir y disfrutar tus infusiones y momentos de calma.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "",
    "netWeight": "",
    "price": 17.0,
    "image": "assets/home-board.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Diseño consciente",
      "Acompaña rituales diarios",
      "Ideal para combinar con Herbal"
    ],
    "ingredients": "Materiales según producto.",
    "conservation": "Lavar y cuidar según material. Evitar golpes o cambios bruscos de temperatura si aplica.",
    "preparation": "Usar como parte de tu ritual de té, infusión o pausa diaria.",
    "moment": "Ritual de té, regalo o pausa consciente en casa.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-LB-001",
    "category": "Wellness",
    "collection": "The Library",
    "subcategory": "Guías",
    "name": "Volver a lo esencial",
    "slug": "volver-a-lo-esencial",
    "description": "Guía digital Volver a lo esencial para cultivar bienestar desde lo esencial.",
    "longDescription": "Volver a lo esencial forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "",
    "netWeight": "",
    "price": 20.0,
    "image": "assets/botanicos-product.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Contenido digital práctico",
      "Diseñado para aplicar en la vida diaria",
      "Acceso simple desde tu cuenta"
    ],
    "ingredients": "Guía digital en formato ebook/PDF.",
    "conservation": "Producto digital. No requiere conservación física.",
    "preparation": "Descargar, leer y aplicar a tu ritmo.",
    "moment": "Lectura personal, planificación semanal o acompañamiento de rituales.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-LB-002",
    "category": "Wellness",
    "collection": "The Library",
    "subcategory": "Guías",
    "name": "21 días para cultivar tu bienestar",
    "slug": "21-dias-para-cultivar-tu-bienestar",
    "description": "Guía digital 21 días para cultivar tu bienestar para cultivar bienestar desde lo esencial.",
    "longDescription": "21 días para cultivar tu bienestar forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "",
    "netWeight": "",
    "price": 30.0,
    "image": "assets/botanicos-product.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Contenido digital práctico",
      "Diseñado para aplicar en la vida diaria",
      "Acceso simple desde tu cuenta"
    ],
    "ingredients": "Guía digital en formato ebook/PDF.",
    "conservation": "Producto digital. No requiere conservación física.",
    "preparation": "Descargar, leer y aplicar a tu ritmo.",
    "moment": "Lectura personal, planificación semanal o acompañamiento de rituales.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-LB-003",
    "category": "Wellness",
    "collection": "The Library",
    "subcategory": "Guías",
    "name": "Cocina desde la raíz",
    "slug": "cocina-desde-la-raiz",
    "description": "Guía digital Cocina desde la raíz para cultivar bienestar desde lo esencial.",
    "longDescription": "Cocina desde la raíz forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "",
    "netWeight": "",
    "price": 25.0,
    "image": "assets/botanicos-product.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Contenido digital práctico",
      "Diseñado para aplicar en la vida diaria",
      "Acceso simple desde tu cuenta"
    ],
    "ingredients": "Guía digital en formato ebook/PDF.",
    "conservation": "Producto digital. No requiere conservación física.",
    "preparation": "Descargar, leer y aplicar a tu ritmo.",
    "moment": "Lectura personal, planificación semanal o acompañamiento de rituales.",
    "relatedHint": "Completa tu ritual"
  },
  {
    "sku": "RA-LB-004",
    "category": "Wellness",
    "collection": "The Library",
    "subcategory": "Guías",
    "name": "Rituales",
    "slug": "rituales",
    "description": "Guía digital Rituales para cultivar bienestar desde lo esencial.",
    "longDescription": "Rituales forma parte de The Library de Raíces: contenido digital creado para acompañar hábitos, cocina consciente, calma y rituales personales.",
    "unit": "Unidad",
    "unitsPerPackage": 1,
    "unitWeight": "",
    "netWeight": "",
    "price": 25.0,
    "image": "assets/botanicos-product.jpg",
    "available": true,
    "taxable": null,
    "benefits": [
      "Contenido digital práctico",
      "Diseñado para aplicar en la vida diaria",
      "Acceso simple desde tu cuenta"
    ],
    "ingredients": "Guía digital en formato ebook/PDF.",
    "conservation": "Producto digital. No requiere conservación física.",
    "preparation": "Descargar, leer y aplicar a tu ritmo.",
    "moment": "Lectura personal, planificación semanal o acompañamiento de rituales.",
    "relatedHint": "Completa tu ritual"
  }
];
