const assert=require('assert');
const {calculateManualTax}=require('./tax-engine');
const tx={mode:'manual_by_state',tax_delivery_when_taxable:true,states:[{country:'US',state:'TX',name:'Texas',rate:'8.25',state_rate:'6.25',nexus:true,active:true}]};
const taxable=[{taxStatus:'physical_taxable',unitCents:2000,qty:1}];
const exempt=[{taxStatus:'food_exempt',unitCents:2000,qty:1}];
const digital=[{taxStatus:'digital_taxable',unitCents:1000,qty:1}];
let r=calculateManualTax({customer:{state:'TX'},items:taxable,deliveryCents:597,salesTax:tx});
assert.equal(r.taxCents,214); assert.equal(r.freightTaxable,true); assert.equal(r.nexus,true);
r=calculateManualTax({customer:{state:'TX'},items:taxable,deliveryCents:0,salesTax:tx});
assert.equal(r.taxCents,165); assert.equal(r.freightTaxable,false);
r=calculateManualTax({customer:{state:'CA'},items:taxable,deliveryCents:597,salesTax:tx});
assert.equal(r.taxCents,0); assert.equal(r.reason,'STATE_NOT_CONFIGURED'); assert.equal(r.nexus,false);
r=calculateManualTax({customer:{state:'TX'},items:exempt,deliveryCents:597,salesTax:tx});
assert.equal(r.taxCents,0); assert.equal(r.reason,'NO_TAXABLE_ITEMS');
r=calculateManualTax({customer:{state:'TX'},items:[...digital,...exempt],deliveryCents:597,salesTax:tx});
assert.equal(r.freightTaxable,false); assert.equal(r.taxCents,83);
r=calculateManualTax({customer:{state:'FL'},items:taxable,deliveryCents:500,salesTax:{...tx,states:[{country:'US',state:'FL',name:'Florida',rate:'6',nexus:false,active:false}]}});
assert.equal(r.taxCents,0); assert.equal(r.reason,'NEXUS_INACTIVE');
console.log('tax-engine tests passed');
