[build]
  publish = "."

[[redirects]]
  from = "/arepas"
  to = "/#arepas"
  status = 200

[[redirects]]
  from = "/empanadas"
  to = "/#empanadas"
  status = 200

[[redirects]]
  from = "/proteinas"
  to = "/#proteinas"
  status = 200

[[redirects]]
  from = "/teas"
  to = "/#tes"
  status = 200

[[redirects]]
  from = "/about"
  to = "/#nosotros"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/#contacto"
  status = 200
